---
title: "Практика"
description: |
  Курс «Анализ данных + R: мир линейных моделей», HSE UX LAB, 2021
author:
  - name: А. Ангельгардт
    url: https://angelgardt.github.io/ru/angelgardt

output: radix::radix_article
---

[Все записи]()


|№|Дата|Тема|Запись|
|:---|:---|:---|:---|
|1|14.01.2021|Введение в R|[Запись]()|
|2|14.01.2021|Типы данных. Векторы|[Запись]()|
|3|21.01.2021|Матрицы и списки|[Запись]()|
|4|21.01.2021|Функции и строки|[Запись]()|
|5|28.01.2021|Датафреймы|[Запись]()|
|6|28.01.2021|Исследование данных|[Запись]()|
|7|4.02.2021|Предобработка данных|[Запись]()|
|8|4.02.2021|Визуализация в ggplot2|[Запись]()|
|9|11.02.2021|Случайный эксперимент|[Запись]()|
|10|11.02.2021|Вероятность и случайные величины|[Запись]()|
|11|18.02.2021|Оценивание параметров в практике статистического анализа|[Запись]()|
|12|18.02.2021|Тестирование статистических гипотез|[Запись]()|
|13|25.02.2021|Описательные статистики|[Запись]()|
|14|25.02.2021|Корреляционный анализ|[Запись]()|
|15|4.03.2021|Простая линейная регрессия|[Запись]()|
|16|4.03.2021|Множественная линейная регрессия|[Запись]()|
|17|11.03.2021|Однофакторный дисперсионный анализ. Ковариационный анализ|[Запись]()|
|18|11.03.2021|Многофакторный дисперсионный анализ. Дисперсионный анализ с повторными измерениями|[Запись]()|
|19|18.03.2021|Обобщённые линейные модели. Логистическая регрессия|[Запись]()|
|20|18.03.2021|Логистическая регрессия|[Запись]()|
|21|25.03.2021|Пуассоновская регрессия|[Запись]()|
|22|25.03.2021|Ridge- и LASSO-регрессия|[Запись]()|
|23|1.04.2021|Смешанные линейные модели (1)|[Запись]()|
|24|1.04.2021|Смешанные линейные модели (2)|[Запись]()|
|25|8.04.2021|Кластерный анализ (1)|[Запись]()|
|26|8.04.2021|Кластерный анализ (2)|[Запись]()|
|27|15.04.2021|Анализ главных компонент|[Запись]()|
|28|15.04.2021|Эксплораторный факторный анализ|[Запись]()|
|29|22.04.2021|Конфирматорный факторный анализ|[Запись]()|
|30|22.04.2021|Обзор путей дальнейшего развития. Обсуждение итогового проекта|[Запись]()|


