<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>28 Конфирматорный факторный анализ | HSE UX LAB | Анализ данных + R: мир линейных моделей | Book</title>
  <meta name="description" content="Книга написана для слушателей курса по анализу данных от HSE UX LAB" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="28 Конфирматорный факторный анализ | HSE UX LAB | Анализ данных + R: мир линейных моделей | Book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Книга написана для слушателей курса по анализу данных от HSE UX LAB" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="28 Конфирматорный факторный анализ | HSE UX LAB | Анализ данных + R: мир линейных моделей | Book" />
  
  <meta name="twitter:description" content="Книга написана для слушателей курса по анализу данных от HSE UX LAB" />
  

<meta name="author" content="А. Ангельгардт" />


<meta name="date" content="2021-01-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="efa.html"/>
<link rel="next" href="further.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="">HSE UX LAB | WLM 2021</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#благодарности"><i class="fa fa-check"></i>Благодарности</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#условные-обозначения"><i class="fa fa-check"></i>Условные обозначения</a></li>
</ul></li>
<li class="part"><span><b>I R programming</b></span></li>
<li class="chapter" data-level="1" data-path="Rintro.html"><a href="Rintro.html"><i class="fa fa-check"></i><b>1</b> Знакомство с R и RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="Rintro.html"><a href="Rintro.html#что-это-и-откуда"><i class="fa fa-check"></i><b>1.1</b> Что это и откуда?</a></li>
<li class="chapter" data-level="1.2" data-path="Rintro.html"><a href="Rintro.html#whyr"><i class="fa fa-check"></i><b>1.2</b> Почему R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="Rintro.html"><a href="Rintro.html#а-он-лучше-питона"><i class="fa fa-check"></i><b>1.2.1</b> А он лучше Питона?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="Rintro.html"><a href="Rintro.html#установка-r-и-rstudio"><i class="fa fa-check"></i><b>1.3</b> Установка R и RStudio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="Rintro.html"><a href="Rintro.html#а-зачем-обе-штуки-ставить"><i class="fa fa-check"></i><b>1.3.1</b> А зачем обе штуки ставить?</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="Rintro.html"><a href="Rintro.html#где-спросить-вопрос-или-искать-ответ"><i class="fa fa-check"></i><b>1.4</b> Где спросить вопрос или искать ответ?</a></li>
<li class="chapter" data-level="1.5" data-path="Rintro.html"><a href="Rintro.html#интерфейс-r"><i class="fa fa-check"></i><b>1.5</b> Интерфейс R</a></li>
<li class="chapter" data-level="1.6" data-path="Rintro.html"><a href="Rintro.html#интерфейс-rstudio"><i class="fa fa-check"></i><b>1.6</b> Интерфейс RStudio</a><ul>
<li class="chapter" data-level="1.6.1" data-path="Rintro.html"><a href="Rintro.html#console"><i class="fa fa-check"></i><b>1.6.1</b> Console</a></li>
<li class="chapter" data-level="1.6.2" data-path="Rintro.html"><a href="Rintro.html#code-editor"><i class="fa fa-check"></i><b>1.6.2</b> Code Editor</a></li>
<li class="chapter" data-level="1.6.3" data-path="Rintro.html"><a href="Rintro.html#environment-workspace-и-history"><i class="fa fa-check"></i><b>1.6.3</b> Environment (Workspace) и History</a></li>
<li class="chapter" data-level="1.6.4" data-path="Rintro.html"><a href="Rintro.html#plots-files-packages-help-viewer"><i class="fa fa-check"></i><b>1.6.4</b> Plots, Files, Packages, Help, Viewer</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="Rintro.html"><a href="Rintro.html#r-как-калькулятор"><i class="fa fa-check"></i><b>1.7</b> R как калькулятор</a><ul>
<li class="chapter" data-level="1.7.1" data-path="Rintro.html"><a href="Rintro.html#арифметические-операции"><i class="fa fa-check"></i><b>1.7.1</b> Арифметические операции</a></li>
<li class="chapter" data-level="1.7.2" data-path="Rintro.html"><a href="Rintro.html#funcs"><i class="fa fa-check"></i><b>1.7.2</b> Функции</a></li>
<li class="chapter" data-level="1.7.3" data-path="Rintro.html"><a href="Rintro.html#сравнение-и-логические-операции"><i class="fa fa-check"></i><b>1.7.3</b> Сравнение и логические операции</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="Rintro.html"><a href="Rintro.html#assignment-и-переменные"><i class="fa fa-check"></i><b>1.8</b> Assignment и переменные</a></li>
<li class="chapter" data-level="1.9" data-path="Rintro.html"><a href="Rintro.html#wd"><i class="fa fa-check"></i><b>1.9</b> Рабочая директория. Projects</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="datatypes.html"><a href="datatypes.html"><i class="fa fa-check"></i><b>2</b> Типы данных</a><ul>
<li class="chapter" data-level="2.1" data-path="datatypes.html"><a href="datatypes.html#numeric"><i class="fa fa-check"></i><b>2.1</b> <code>numeric</code></a></li>
<li class="chapter" data-level="2.2" data-path="datatypes.html"><a href="datatypes.html#logical"><i class="fa fa-check"></i><b>2.2</b> <code>logical</code></a></li>
<li class="chapter" data-level="2.3" data-path="datatypes.html"><a href="datatypes.html#character"><i class="fa fa-check"></i><b>2.3</b> <code>character</code></a></li>
<li class="chapter" data-level="2.4" data-path="datatypes.html"><a href="datatypes.html#factors"><i class="fa fa-check"></i><b>2.4</b> <code>factor</code></a></li>
<li class="chapter" data-level="2.5" data-path="datatypes.html"><a href="datatypes.html#coercion-part-one"><i class="fa fa-check"></i><b>2.5</b> Coercion [part one]</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="datastructures.html"><a href="datastructures.html"><i class="fa fa-check"></i><b>3</b> Структуры данных</a><ul>
<li class="chapter" data-level="3.1" data-path="datastructures.html"><a href="datastructures.html#векторы"><i class="fa fa-check"></i><b>3.1</b> Векторы</a><ul>
<li class="chapter" data-level="3.1.1" data-path="datastructures.html"><a href="datastructures.html#coercion-part-two"><i class="fa fa-check"></i><b>3.1.1</b> Coercion [part two]</a></li>
<li class="chapter" data-level="3.1.2" data-path="datastructures.html"><a href="datastructures.html#генерация-числовых-последовательностей"><i class="fa fa-check"></i><b>3.1.2</b> Генерация числовых последовательностей</a></li>
<li class="chapter" data-level="3.1.3" data-path="datastructures.html"><a href="datastructures.html#операции-с-векторами"><i class="fa fa-check"></i><b>3.1.3</b> Операции с векторами</a></li>
<li class="chapter" data-level="3.1.4" data-path="datastructures.html"><a href="datastructures.html#recycling"><i class="fa fa-check"></i><b>3.1.4</b> Recycling</a></li>
<li class="chapter" data-level="3.1.5" data-path="datastructures.html"><a href="datastructures.html#индексация-векторов"><i class="fa fa-check"></i><b>3.1.5</b> Индексация векторов</a></li>
<li class="chapter" data-level="3.1.6" data-path="datastructures.html"><a href="datastructures.html#na-nan-null"><i class="fa fa-check"></i><b>3.1.6</b> NA, NaN, NULL</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="datastructures.html"><a href="datastructures.html#матрицы"><i class="fa fa-check"></i><b>3.2</b> Матрицы</a><ul>
<li class="chapter" data-level="3.2.1" data-path="datastructures.html"><a href="datastructures.html#индексация-матриц"><i class="fa fa-check"></i><b>3.2.1</b> Индексация матриц</a></li>
<li class="chapter" data-level="3.2.2" data-path="datastructures.html"><a href="datastructures.html#операции-в-матрицами"><i class="fa fa-check"></i><b>3.2.2</b> Операции в матрицами</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="datastructures.html"><a href="datastructures.html#списки"><i class="fa fa-check"></i><b>3.3</b> Списки</a><ul>
<li class="chapter" data-level="3.3.1" data-path="datastructures.html"><a href="datastructures.html#индексация-списков"><i class="fa fa-check"></i><b>3.3.1</b> Индексация списков</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="datastructures.html"><a href="datastructures.html#датафреймы"><i class="fa fa-check"></i><b>3.4</b> Датафреймы</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Функции</a><ul>
<li class="chapter" data-level="4.1" data-path="functions.html"><a href="functions.html#открытый-исходный-код"><i class="fa fa-check"></i><b>4.1</b> Открытый исходный код</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>5</b> Строки</a><ul>
<li class="chapter" data-level="5.1" data-path="strings.html"><a href="strings.html#установка-дополнительных-пакетов"><i class="fa fa-check"></i><b>5.1</b> Установка дополнительных пакетов</a></li>
<li class="chapter" data-level="5.2" data-path="strings.html"><a href="strings.html#создание-строк"><i class="fa fa-check"></i><b>5.2</b> Создание строк</a></li>
<li class="chapter" data-level="5.3" data-path="strings.html"><a href="strings.html#конкатенация-строк"><i class="fa fa-check"></i><b>5.3</b> Конкатенация строк</a></li>
<li class="chapter" data-level="5.4" data-path="strings.html"><a href="strings.html#разделение-строк"><i class="fa fa-check"></i><b>5.4</b> Разделение строк</a></li>
<li class="chapter" data-level="5.5" data-path="strings.html"><a href="strings.html#сортировка-строк"><i class="fa fa-check"></i><b>5.5</b> Сортировка строк</a></li>
<li class="chapter" data-level="5.6" data-path="strings.html"><a href="strings.html#изменение-регистра"><i class="fa fa-check"></i><b>5.6</b> Изменение регистра</a></li>
<li class="chapter" data-level="5.7" data-path="strings.html"><a href="strings.html#поиск-подстроки"><i class="fa fa-check"></i><b>5.7</b> Поиск подстроки</a></li>
<li class="chapter" data-level="5.8" data-path="strings.html"><a href="strings.html#изменение-строк"><i class="fa fa-check"></i><b>5.8</b> Изменение строк</a><ul>
<li class="chapter" data-level="5.8.1" data-path="strings.html"><a href="strings.html#выделение-подстроки"><i class="fa fa-check"></i><b>5.8.1</b> Выделение подстроки</a></li>
<li class="chapter" data-level="5.8.2" data-path="strings.html"><a href="strings.html#замена-подстроки"><i class="fa fa-check"></i><b>5.8.2</b> Замена подстроки</a></li>
<li class="chapter" data-level="5.8.3" data-path="strings.html"><a href="strings.html#удаление-подстроки"><i class="fa fa-check"></i><b>5.8.3</b> Удаление подстроки</a></li>
<li class="chapter" data-level="5.8.4" data-path="strings.html"><a href="strings.html#транслитерация-строк"><i class="fa fa-check"></i><b>5.8.4</b> Транслитерация строк</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="strings.html"><a href="strings.html#регулярные-выражения"><i class="fa fa-check"></i><b>5.9</b> Регулярные выражения</a><ul>
<li class="chapter" data-level="5.9.1" data-path="strings.html"><a href="strings.html#метасимволы"><i class="fa fa-check"></i><b>5.9.1</b> Метасимволы</a></li>
<li class="chapter" data-level="5.9.2" data-path="strings.html"><a href="strings.html#классы-знаков"><i class="fa fa-check"></i><b>5.9.2</b> Классы знаков</a></li>
<li class="chapter" data-level="5.9.3" data-path="strings.html"><a href="strings.html#quant"><i class="fa fa-check"></i><b>5.9.3</b> Квантификация</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="realdata.html"><a href="realdata.html"><i class="fa fa-check"></i><b>6</b> Работа с реальными данными</a><ul>
<li class="chapter" data-level="6.1" data-path="realdata.html"><a href="realdata.html#рабочая-директория"><i class="fa fa-check"></i><b>6.1</b> Рабочая директория</a></li>
<li class="chapter" data-level="6.2" data-path="realdata.html"><a href="realdata.html#импорт-данных"><i class="fa fa-check"></i><b>6.2</b> Импорт данных</a><ul>
<li class="chapter" data-level="6.2.1" data-path="realdata.html"><a href="realdata.html#форматы-данных"><i class="fa fa-check"></i><b>6.2.1</b> Форматы данных</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="realdata.html"><a href="realdata.html#исследование-данных"><i class="fa fa-check"></i><b>6.3</b> Исследование данных</a></li>
<li class="chapter" data-level="6.4" data-path="realdata.html"><a href="realdata.html#файл-.rdata"><i class="fa fa-check"></i><b>6.4</b> Файл <code>.RData</code></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>7</b> Предобработка данных. Концепция tidy data</a><ul>
<li class="chapter" data-level="7.1" data-path="tidy.html"><a href="tidy.html#tidyverse"><i class="fa fa-check"></i><b>7.1</b> <code>tidyverse</code></a></li>
<li class="chapter" data-level="7.2" data-path="tidy.html"><a href="tidy.html#импорт-данных-1"><i class="fa fa-check"></i><b>7.2</b> Импорт данных</a></li>
<li class="chapter" data-level="7.3" data-path="tidy.html"><a href="tidy.html#tibble"><i class="fa fa-check"></i><b>7.3</b> <code>tibble</code></a></li>
<li class="chapter" data-level="7.4" data-path="tidy.html"><a href="tidy.html#грузим-много-данных"><i class="fa fa-check"></i><b>7.4</b> Грузим много данных</a></li>
<li class="chapter" data-level="7.5" data-path="tidy.html"><a href="tidy.html#сабсет-данных"><i class="fa fa-check"></i><b>7.5</b> Сабсет данных</a><ul>
<li class="chapter" data-level="7.5.1" data-path="tidy.html"><a href="tidy.html#pipe"><i class="fa fa-check"></i><b>7.5.1</b> <code>%&gt;%</code></a></li>
<li class="chapter" data-level="7.5.2" data-path="tidy.html"><a href="tidy.html#select"><i class="fa fa-check"></i><b>7.5.2</b> <code>select()</code></a></li>
<li class="chapter" data-level="7.5.3" data-path="tidy.html"><a href="tidy.html#rename"><i class="fa fa-check"></i><b>7.5.3</b> <code>rename()</code></a></li>
<li class="chapter" data-level="7.5.4" data-path="tidy.html"><a href="tidy.html#slice"><i class="fa fa-check"></i><b>7.5.4</b> <code>slice()</code></a></li>
<li class="chapter" data-level="7.5.5" data-path="tidy.html"><a href="tidy.html#filter"><i class="fa fa-check"></i><b>7.5.5</b> <code>filter()</code></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="tidy.html"><a href="tidy.html#mutate"><i class="fa fa-check"></i><b>7.6</b> <code>mutate()</code></a></li>
<li class="chapter" data-level="7.7" data-path="tidy.html"><a href="tidy.html#догрузим-остальные-данные"><i class="fa fa-check"></i><b>7.7</b> Догрузим остальные данные</a><ul>
<li class="chapter" data-level="7.7.1" data-path="tidy.html"><a href="tidy.html#соединение-датафреймов-i"><i class="fa fa-check"></i><b>7.7.1</b> Соединение датафреймов I</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="tidy.html"><a href="tidy.html#сортировка"><i class="fa fa-check"></i><b>7.8</b> Сортировка</a><ul>
<li class="chapter" data-level="7.8.1" data-path="tidy.html"><a href="tidy.html#sort"><i class="fa fa-check"></i><b>7.8.1</b> <code>sort()</code></a></li>
<li class="chapter" data-level="7.8.2" data-path="tidy.html"><a href="tidy.html#arrange"><i class="fa fa-check"></i><b>7.8.2</b> <code>arrange()</code></a></li>
<li class="chapter" data-level="7.8.3" data-path="tidy.html"><a href="tidy.html#distinct"><i class="fa fa-check"></i><b>7.8.3</b> <code>distinct()</code></a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="tidy.html"><a href="tidy.html#соединение-датафреймов-ii"><i class="fa fa-check"></i><b>7.9</b> Соединение датафреймов II</a><ul>
<li class="chapter" data-level="7.9.1" data-path="tidy.html"><a href="tidy.html#join"><i class="fa fa-check"></i><b>7.9.1</b> <code>..._join()</code></a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="tidy.html"><a href="tidy.html#группировка-и-аггрегация-данных"><i class="fa fa-check"></i><b>7.10</b> Группировка и аггрегация данных</a><ul>
<li class="chapter" data-level="7.10.1" data-path="tidy.html"><a href="tidy.html#group_by-ungroup"><i class="fa fa-check"></i><b>7.10.1</b> <code>group_by()</code> &amp; <code>ungroup()</code></a></li>
<li class="chapter" data-level="7.10.2" data-path="tidy.html"><a href="tidy.html#summarize"><i class="fa fa-check"></i><b>7.10.2</b> <code>summarize()</code></a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="tidy.html"><a href="tidy.html#широкий-и-длинный-формат"><i class="fa fa-check"></i><b>7.11</b> Широкий и длинный формат</a><ul>
<li class="chapter" data-level="7.11.1" data-path="tidy.html"><a href="tidy.html#pivot_longer-pivot_wider"><i class="fa fa-check"></i><b>7.11.1</b> <code>pivot_longer()</code> &amp; <code>pivot_wider()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>8</b> Визуализация данных</a><ul>
<li class="chapter" data-level="8.1" data-path="visualization.html"><a href="visualization.html#философия-ggplot2-a-layered-grammar-of-graphics"><i class="fa fa-check"></i><b>8.1</b> Философия ggplot2 (A Layered Grammar of Graphics)</a><ul>
<li class="chapter" data-level="8.1.1" data-path="visualization.html"><a href="visualization.html#собственно-к-философии-построения-графиков"><i class="fa fa-check"></i><b>8.1.1</b> Собственно к философии построения графиков</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="visualization.html"><a href="visualization.html#данные"><i class="fa fa-check"></i><b>8.2</b> Данные</a></li>
<li class="chapter" data-level="8.3" data-path="visualization.html"><a href="visualization.html#строим-базовый-график"><i class="fa fa-check"></i><b>8.3</b> Строим базовый график</a><ul>
<li class="chapter" data-level="8.3.1" data-path="visualization.html"><a href="visualization.html#базовый-слой"><i class="fa fa-check"></i><b>8.3.1</b> Базовый слой</a></li>
<li class="chapter" data-level="8.3.2" data-path="visualization.html"><a href="visualization.html#разметка-осей-и-переменные"><i class="fa fa-check"></i><b>8.3.2</b> Разметка осей и переменные</a></li>
<li class="chapter" data-level="8.3.3" data-path="visualization.html"><a href="visualization.html#геомы"><i class="fa fa-check"></i><b>8.3.3</b> Геомы</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="visualization.html"><a href="visualization.html#группировка-по-переменной"><i class="fa fa-check"></i><b>8.4</b> Группировка по переменной</a></li>
<li class="chapter" data-level="8.5" data-path="visualization.html"><a href="visualization.html#графики-со-встроенной-статистической-обработкой"><i class="fa fa-check"></i><b>8.5</b> Графики со встроенной статистической обработкой</a><ul>
<li class="chapter" data-level="8.5.1" data-path="visualization.html"><a href="visualization.html#статы-stat_"><i class="fa fa-check"></i><b>8.5.1</b> Статы (stat_)</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="visualization.html"><a href="visualization.html#ищем-более-сложные-закономерности"><i class="fa fa-check"></i><b>8.6</b> Ищем более сложные закономерности</a></li>
<li class="chapter" data-level="8.7" data-path="visualization.html"><a href="visualization.html#настраиваем-график"><i class="fa fa-check"></i><b>8.7</b> Настраиваем график</a><ul>
<li class="chapter" data-level="8.7.1" data-path="visualization.html"><a href="visualization.html#темы"><i class="fa fa-check"></i><b>8.7.1</b> Темы</a></li>
<li class="chapter" data-level="8.7.2" data-path="visualization.html"><a href="visualization.html#кастомизация-шкал-scale_"><i class="fa fa-check"></i><b>8.7.2</b> Кастомизация шкал (scale_)</a></li>
<li class="chapter" data-level="8.7.3" data-path="visualization.html"><a href="visualization.html#последние-штрихи"><i class="fa fa-check"></i><b>8.7.3</b> Последние штрихи</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="visualization.html"><a href="visualization.html#больше-переменных"><i class="fa fa-check"></i><b>8.8</b> Больше переменных</a><ul>
<li class="chapter" data-level="8.8.1" data-path="visualization.html"><a href="visualization.html#фасетизация"><i class="fa fa-check"></i><b>8.8.1</b> Фасетизация</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="visualization.html"><a href="visualization.html#сохранение-графиков"><i class="fa fa-check"></i><b>8.9</b> Сохранение графиков</a></li>
<li class="chapter" data-level="8.10" data-path="visualization.html"><a href="visualization.html#другие-геомы"><i class="fa fa-check"></i><b>8.10</b> Другие геомы</a></li>
</ul></li>
<li class="part"><span><b>II Теория вероятностей и математическая статистика</b></span></li>
<li class="chapter" data-level="9" data-path="maths.html"><a href="maths.html"><i class="fa fa-check"></i><b>9</b> Математический ликбез</a><ul>
<li class="chapter" data-level="9.1" data-path="maths.html"><a href="maths.html#alg_logic"><i class="fa fa-check"></i><b>9.1</b> Элементы алгебры логики</a><ul>
<li class="chapter" data-level="9.1.1" data-path="maths.html"><a href="maths.html#высказывания"><i class="fa fa-check"></i><b>9.1.1</b> Высказывания</a></li>
<li class="chapter" data-level="9.1.2" data-path="maths.html"><a href="maths.html#logic_operations"><i class="fa fa-check"></i><b>9.1.2</b> Логические операции</a></li>
<li class="chapter" data-level="9.1.3" data-path="maths.html"><a href="maths.html#сложные-высказвания"><i class="fa fa-check"></i><b>9.1.3</b> Сложные высказвания</a></li>
<li class="chapter" data-level="9.1.4" data-path="maths.html"><a href="maths.html#условные-высказывания"><i class="fa fa-check"></i><b>9.1.4</b> Условные высказывания</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="maths.html"><a href="maths.html#set_theory"><i class="fa fa-check"></i><b>9.2</b> Элементы теории множеств</a><ul>
<li class="chapter" data-level="9.2.1" data-path="maths.html"><a href="maths.html#set"><i class="fa fa-check"></i><b>9.2.1</b> Множество</a></li>
<li class="chapter" data-level="9.2.2" data-path="maths.html"><a href="maths.html#sets_operations"><i class="fa fa-check"></i><b>9.2.2</b> Операции над множествами</a></li>
<li class="chapter" data-level="9.2.3" data-path="maths.html"><a href="maths.html#отображения"><i class="fa fa-check"></i><b>9.2.3</b> Отображения</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="maths.html"><a href="maths.html#combinatorics"><i class="fa fa-check"></i><b>9.3</b> Немного комбинаторики</a><ul>
<li class="chapter" data-level="9.3.1" data-path="maths.html"><a href="maths.html#permutations"><i class="fa fa-check"></i><b>9.3.1</b> Перестановки</a></li>
<li class="chapter" data-level="9.3.2" data-path="maths.html"><a href="maths.html#accomodations"><i class="fa fa-check"></i><b>9.3.2</b> Размещения</a></li>
<li class="chapter" data-level="9.3.3" data-path="maths.html"><a href="maths.html#combinations"><i class="fa fa-check"></i><b>9.3.3</b> Сочетания</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="maths.html"><a href="maths.html#calculus"><i class="fa fa-check"></i><b>9.4</b> Элементы математического анализа</a><ul>
<li class="chapter" data-level="9.4.1" data-path="maths.html"><a href="maths.html#последовательность"><i class="fa fa-check"></i><b>9.4.1</b> Последовательность</a></li>
<li class="chapter" data-level="9.4.2" data-path="maths.html"><a href="maths.html#предел-последовательности"><i class="fa fa-check"></i><b>9.4.2</b> Предел последовательности</a></li>
<li class="chapter" data-level="9.4.3" data-path="maths.html"><a href="maths.html#функции"><i class="fa fa-check"></i><b>9.4.3</b> Функции</a></li>
<li class="chapter" data-level="9.4.4" data-path="maths.html"><a href="maths.html#дифференцируемость-функции.-производная"><i class="fa fa-check"></i><b>9.4.4</b> Дифференцируемость функции. Производная</a></li>
<li class="chapter" data-level="9.4.5" data-path="maths.html"><a href="maths.html#функции-нескольких-переменных"><i class="fa fa-check"></i><b>9.4.5</b> Функции нескольких переменных</a></li>
<li class="chapter" data-level="9.4.6" data-path="maths.html"><a href="maths.html#partial"><i class="fa fa-check"></i><b>9.4.6</b> Частные производные</a></li>
<li class="chapter" data-level="9.4.7" data-path="maths.html"><a href="maths.html#интеграл"><i class="fa fa-check"></i><b>9.4.7</b> Интеграл</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="maths.html"><a href="maths.html#matrix"><i class="fa fa-check"></i><b>9.5</b> Элементы линейной алгебры</a><ul>
<li class="chapter" data-level="9.5.1" data-path="maths.html"><a href="maths.html#что-такое-матрица"><i class="fa fa-check"></i><b>9.5.1</b> Что такое матрица?</a></li>
<li class="chapter" data-level="9.5.2" data-path="maths.html"><a href="maths.html#откуда-берутся-матрицы"><i class="fa fa-check"></i><b>9.5.2</b> Откуда берутся матрицы?</a></li>
<li class="chapter" data-level="9.5.3" data-path="maths.html"><a href="maths.html#действия-с-матрицами"><i class="fa fa-check"></i><b>9.5.3</b> Действия с матрицами</a></li>
<li class="chapter" data-level="9.5.4" data-path="maths.html"><a href="maths.html#скалярное-произведение-векторов"><i class="fa fa-check"></i><b>9.5.4</b> Скалярное произведение векторов</a></li>
<li class="chapter" data-level="9.5.5" data-path="maths.html"><a href="maths.html#векторное-произведение-векторов"><i class="fa fa-check"></i><b>9.5.5</b> Векторное произведение векторов</a></li>
<li class="chapter" data-level="9.5.6" data-path="maths.html"><a href="maths.html#произведение-матриц-матричное-умножение"><i class="fa fa-check"></i><b>9.5.6</b> Произведение матриц (матричное умножение)</a></li>
<li class="chapter" data-level="9.5.7" data-path="maths.html"><a href="maths.html#транспонирование-матрицы"><i class="fa fa-check"></i><b>9.5.7</b> Транспонирование матрицы</a></li>
<li class="chapter" data-level="9.5.8" data-path="maths.html"><a href="maths.html#inv"><i class="fa fa-check"></i><b>9.5.8</b> Детерминант и обратная матрица</a></li>
<li class="chapter" data-level="9.5.9" data-path="maths.html"><a href="maths.html#след-матрицы"><i class="fa fa-check"></i><b>9.5.9</b> След матрицы</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="stats-intro.html"><a href="stats-intro.html"><i class="fa fa-check"></i><b>10</b> Введение в статистику</a><ul>
<li class="chapter" data-level="10.1" data-path="stats-intro.html"><a href="stats-intro.html#исходные-понятия-статистики"><i class="fa fa-check"></i><b>10.1</b> Исходные понятия статистики</a></li>
<li class="chapter" data-level="10.2" data-path="stats-intro.html"><a href="stats-intro.html#виды-статистических-данных"><i class="fa fa-check"></i><b>10.2</b> Виды статистических данных</a></li>
<li class="chapter" data-level="10.3" data-path="stats-intro.html"><a href="stats-intro.html#шкалы"><i class="fa fa-check"></i><b>10.3</b> Шкалы</a></li>
<li class="chapter" data-level="10.4" data-path="stats-intro.html"><a href="stats-intro.html#задачи-статистики"><i class="fa fa-check"></i><b>10.4</b> Задачи статистики</a><ul>
<li class="chapter" data-level="10.4.1" data-path="stats-intro.html"><a href="stats-intro.html#этапы-статистического-моделирования"><i class="fa fa-check"></i><b>10.4.1</b> Этапы статистического моделирования</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="randexp.html"><a href="randexp.html"><i class="fa fa-check"></i><b>11</b> Случайный эксперимент</a><ul>
<li class="chapter" data-level="11.1" data-path="randexp.html"><a href="randexp.html#ход-исследования"><i class="fa fa-check"></i><b>11.1</b> Ход исследования</a></li>
<li class="chapter" data-level="11.2" data-path="randexp.html"><a href="randexp.html#событие.-пространство-элементарных-событий."><i class="fa fa-check"></i><b>11.2</b> Событие. Пространство элементарных событий.</a><ul>
<li class="chapter" data-level="11.2.1" data-path="randexp.html"><a href="randexp.html#игральный-кубик"><i class="fa fa-check"></i><b>11.2.1</b> Игральный кубик</a></li>
<li class="chapter" data-level="11.2.2" data-path="randexp.html"><a href="randexp.html#events_operations"><i class="fa fa-check"></i><b>11.2.2</b> Действия над событиями</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="randexp.html"><a href="randexp.html#классическое-определение-вероятности"><i class="fa fa-check"></i><b>11.3</b> Классическое определение вероятности</a></li>
<li class="chapter" data-level="11.4" data-path="randexp.html"><a href="randexp.html#статистическое-определение-вероятности"><i class="fa fa-check"></i><b>11.4</b> Статистическое определение вероятности</a></li>
<li class="chapter" data-level="11.5" data-path="randexp.html"><a href="randexp.html#кроме-кубика"><i class="fa fa-check"></i><b>11.5</b> Кроме кубика</a></li>
<li class="chapter" data-level="11.6" data-path="randexp.html"><a href="randexp.html#вероятности-сложных-событий"><i class="fa fa-check"></i><b>11.6</b> Вероятности сложных событий</a><ul>
<li class="chapter" data-level="11.6.1" data-path="randexp.html"><a href="randexp.html#условная-вероятность"><i class="fa fa-check"></i><b>11.6.1</b> Условная вероятность</a></li>
<li class="chapter" data-level="11.6.2" data-path="randexp.html"><a href="randexp.html#теорема-байеса"><i class="fa fa-check"></i><b>11.6.2</b> Теорема Байеса</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="prob.html"><a href="prob.html"><i class="fa fa-check"></i><b>12</b> Вероятность и случайные величины</a><ul>
<li class="chapter" data-level="12.1" data-path="prob.html"><a href="prob.html#дискретные-случайные-величины"><i class="fa fa-check"></i><b>12.1</b> Дискретные случайные величины</a></li>
<li class="chapter" data-level="12.2" data-path="prob.html"><a href="prob.html#непрерывные-случайные-величины"><i class="fa fa-check"></i><b>12.2</b> Непрерывные случайные величины</a></li>
<li class="chapter" data-level="12.3" data-path="prob.html"><a href="prob.html#moments_distributions"><i class="fa fa-check"></i><b>12.3</b> Характеристики распределения случайных величин</a></li>
<li class="chapter" data-level="12.4" data-path="prob.html"><a href="prob.html#normal_distribution"><i class="fa fa-check"></i><b>12.4</b> Нормальное распределение</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="statestim.html"><a href="statestim.html"><i class="fa fa-check"></i><b>13</b> Оценивание параметров в практике статистического анализа</a><ul>
<li class="chapter" data-level="13.1" data-path="statestim.html"><a href="statestim.html#точечные-оценки"><i class="fa fa-check"></i><b>13.1</b> Точечные оценки</a><ul>
<li class="chapter" data-level="13.1.1" data-path="statestim.html"><a href="statestim.html#метод-моментов"><i class="fa fa-check"></i><b>13.1.1</b> Метод моментов</a></li>
<li class="chapter" data-level="13.1.2" data-path="statestim.html"><a href="statestim.html#свойства-точечных-оценок"><i class="fa fa-check"></i><b>13.1.2</b> Свойства точечных оценок</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="statestim.html"><a href="statestim.html#интервальные-оценки"><i class="fa fa-check"></i><b>13.2</b> Интервальные оценки</a><ul>
<li class="chapter" data-level="13.2.1" data-path="statestim.html"><a href="statestim.html#confinterval"><i class="fa fa-check"></i><b>13.2.1</b> Доверительный интервал</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>14</b> Тестирование статистических гипотез</a><ul>
<li class="chapter" data-level="14.1" data-path="hypotheses.html"><a href="hypotheses.html#базовые-понятия"><i class="fa fa-check"></i><b>14.1</b> Базовые понятия</a></li>
<li class="chapter" data-level="14.2" data-path="hypotheses.html"><a href="hypotheses.html#асимметрия-статистического-вывода"><i class="fa fa-check"></i><b>14.2</b> Асимметрия статистического вывода</a></li>
<li class="chapter" data-level="14.3" data-path="hypotheses.html"><a href="hypotheses.html#возможные-результаты-проверки-гипотез"><i class="fa fa-check"></i><b>14.3</b> Возможные результаты проверки гипотез</a></li>
<li class="chapter" data-level="14.4" data-path="hypotheses.html"><a href="hypotheses.html#алгоритм-тестирования-статистических-гипотез"><i class="fa fa-check"></i><b>14.4</b> Алгоритм тестирования статистических гипотез</a></li>
<li class="chapter" data-level="14.5" data-path="hypotheses.html"><a href="hypotheses.html#multiple_comp_problem"><i class="fa fa-check"></i><b>14.5</b> Проблема множественных сравнений</a></li>
</ul></li>
<li class="part"><span><b>III Анализ данных</b></span></li>
<li class="chapter" data-level="15" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>15</b> Описательные статистики</a><ul>
<li class="chapter" data-level="15.1" data-path="descriptives.html"><a href="descriptives.html#меры-центральной-тенденции"><i class="fa fa-check"></i><b>15.1</b> Меры центральной тенденции</a><ul>
<li class="chapter" data-level="15.1.1" data-path="descriptives.html"><a href="descriptives.html#мода"><i class="fa fa-check"></i><b>15.1.1</b> Мода</a></li>
<li class="chapter" data-level="15.1.2" data-path="descriptives.html"><a href="descriptives.html#медиана"><i class="fa fa-check"></i><b>15.1.2</b> Медиана</a></li>
<li class="chapter" data-level="15.1.3" data-path="descriptives.html"><a href="descriptives.html#среднее"><i class="fa fa-check"></i><b>15.1.3</b> Среднее</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="descriptives.html"><a href="descriptives.html#меры-разброса"><i class="fa fa-check"></i><b>15.2</b> Меры разброса</a><ul>
<li class="chapter" data-level="15.2.1" data-path="descriptives.html"><a href="descriptives.html#минимум-и-максимум"><i class="fa fa-check"></i><b>15.2.1</b> Минимум и максимум</a></li>
<li class="chapter" data-level="15.2.2" data-path="descriptives.html"><a href="descriptives.html#размах"><i class="fa fa-check"></i><b>15.2.2</b> Размах</a></li>
<li class="chapter" data-level="15.2.3" data-path="descriptives.html"><a href="descriptives.html#дисперсия"><i class="fa fa-check"></i><b>15.2.3</b> Дисперсия</a></li>
<li class="chapter" data-level="15.2.4" data-path="descriptives.html"><a href="descriptives.html#стандартное-отклонение"><i class="fa fa-check"></i><b>15.2.4</b> Стандартное отклонение</a></li>
<li class="chapter" data-level="15.2.5" data-path="descriptives.html"><a href="descriptives.html#стандартная-ошибка-среднего"><i class="fa fa-check"></i><b>15.2.5</b> Стандартная ошибка среднего</a></li>
<li class="chapter" data-level="15.2.6" data-path="descriptives.html"><a href="descriptives.html#квантили"><i class="fa fa-check"></i><b>15.2.6</b> Квантили</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="descriptives.html"><a href="descriptives.html#асимметрия"><i class="fa fa-check"></i><b>15.3</b> Асимметрия</a></li>
<li class="chapter" data-level="15.4" data-path="descriptives.html"><a href="descriptives.html#эксцесс"><i class="fa fa-check"></i><b>15.4</b> Эксцесс</a></li>
<li class="chapter" data-level="15.5" data-path="descriptives.html"><a href="descriptives.html#описательные-статистики-в-r"><i class="fa fa-check"></i><b>15.5</b> Описательные статистики в R</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>16</b> Корреляционный анализ</a><ul>
<li class="chapter" data-level="16.1" data-path="correlation.html"><a href="correlation.html#ковариация"><i class="fa fa-check"></i><b>16.1</b> Ковариация</a></li>
<li class="chapter" data-level="16.2" data-path="correlation.html"><a href="correlation.html#корреляция"><i class="fa fa-check"></i><b>16.2</b> Корреляция</a><ul>
<li class="chapter" data-level="16.2.1" data-path="correlation.html"><a href="correlation.html#тестирование-статистической-значимости-коэффициента-корреляции"><i class="fa fa-check"></i><b>16.2.1</b> Тестирование статистической значимости коэффициента корреляции</a></li>
<li class="chapter" data-level="16.2.2" data-path="correlation.html"><a href="correlation.html#доверительный-интервал-для-коэффициента-корреляции"><i class="fa fa-check"></i><b>16.2.2</b> Доверительный интервал для коэффициента корреляции</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="correlation.html"><a href="correlation.html#ковариация-и-корреляция-в-r"><i class="fa fa-check"></i><b>16.3</b> Ковариация и корреляция в R</a><ul>
<li class="chapter" data-level="16.3.1" data-path="correlation.html"><a href="correlation.html#коэффициенты-корреляции-для-разных-шкал"><i class="fa fa-check"></i><b>16.3.1</b> Коэффициенты корреляции для разных шкал</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="correlation.html"><a href="correlation.html#частный-и-множественный-коэффициент-корреляции"><i class="fa fa-check"></i><b>16.4</b> Частный и множественный коэффициент корреляции</a></li>
<li class="chapter" data-level="16.5" data-path="correlation.html"><a href="correlation.html#другие-корреляции"><i class="fa fa-check"></i><b>16.5</b> Другие корреляции</a><ul>
<li class="chapter" data-level="16.5.1" data-path="correlation.html"><a href="correlation.html#phi-коэффициент"><i class="fa fa-check"></i><b>16.5.1</b> <span class="math inline">\(\phi\)</span>-коэффициент</a></li>
<li class="chapter" data-level="16.5.2" data-path="correlation.html"><a href="correlation.html#бисериальный-коэффициент-корреляции"><i class="fa fa-check"></i><b>16.5.2</b> Бисериальный коэффициент корреляции</a></li>
<li class="chapter" data-level="16.5.3" data-path="correlation.html"><a href="correlation.html#рангово-бисериальный-коэффициент-корреляции"><i class="fa fa-check"></i><b>16.5.3</b> Рангово-бисериальный коэффициент корреляции</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="simple-linear.html"><a href="simple-linear.html"><i class="fa fa-check"></i><b>17</b> Общие линейные модели. Простая линейная регрессия</a><ul>
<li class="chapter" data-level="17.1" data-path="simple-linear.html"><a href="simple-linear.html#формализация-модели"><i class="fa fa-check"></i><b>17.1</b> Формализация модели</a></li>
<li class="chapter" data-level="17.2" data-path="simple-linear.html"><a href="simple-linear.html#идентификация-модели"><i class="fa fa-check"></i><b>17.2</b> Идентификация модели</a><ul>
<li class="chapter" data-level="17.2.1" data-path="simple-linear.html"><a href="simple-linear.html#метод-наименьших-квадратов"><i class="fa fa-check"></i><b>17.2.1</b> Метод наименьших квадратов</a></li>
<li class="chapter" data-level="17.2.2" data-path="simple-linear.html"><a href="simple-linear.html#матричное-вычисление-коэффициентов"><i class="fa fa-check"></i><b>17.2.2</b> Матричное вычисление коэффициентов</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="simple-linear.html"><a href="simple-linear.html#тестирование-качества-модели"><i class="fa fa-check"></i><b>17.3</b> Тестирование качества модели</a><ul>
<li class="chapter" data-level="17.3.1" data-path="simple-linear.html"><a href="simple-linear.html#коэффициент-детерминации"><i class="fa fa-check"></i><b>17.3.1</b> Коэффициент детерминации</a></li>
<li class="chapter" data-level="17.3.2" data-path="simple-linear.html"><a href="simple-linear.html#статистическая-значимость-модели"><i class="fa fa-check"></i><b>17.3.2</b> Статистическая значимость модели</a></li>
<li class="chapter" data-level="17.3.3" data-path="simple-linear.html"><a href="simple-linear.html#статистическая-значимость-отдельных-предикторов"><i class="fa fa-check"></i><b>17.3.3</b> Статистическая значимость отдельных предикторов</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="simple-linear.html"><a href="simple-linear.html#простая-линейная-регрессия-в-r"><i class="fa fa-check"></i><b>17.4</b> Простая линейная регрессия в R</a></li>
<li class="chapter" data-level="17.5" data-path="simple-linear.html"><a href="simple-linear.html#диагностика-модели"><i class="fa fa-check"></i><b>17.5</b> Диагностика модели</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="multiple-linear.html"><a href="multiple-linear.html"><i class="fa fa-check"></i><b>18</b> Множественная линейная регрессия</a><ul>
<li class="chapter" data-level="18.1" data-path="multiple-linear.html"><a href="multiple-linear.html#множественная-линейная-регрессия-с-количественными-предикторами"><i class="fa fa-check"></i><b>18.1</b> Множественная линейная регрессия с количественными предикторами</a><ul>
<li class="chapter" data-level="18.1.1" data-path="multiple-linear.html"><a href="multiple-linear.html#математическая-модель"><i class="fa fa-check"></i><b>18.1.1</b> Математическая модель</a></li>
<li class="chapter" data-level="18.1.2" data-path="multiple-linear.html"><a href="multiple-linear.html#подбор-модели"><i class="fa fa-check"></i><b>18.1.2</b> Подбор модели</a></li>
<li class="chapter" data-level="18.1.3" data-path="multiple-linear.html"><a href="multiple-linear.html#оценка-качества-модели"><i class="fa fa-check"></i><b>18.1.3</b> Оценка качества модели</a></li>
<li class="chapter" data-level="18.1.4" data-path="multiple-linear.html"><a href="multiple-linear.html#диагностика-модели-1"><i class="fa fa-check"></i><b>18.1.4</b> Диагностика модели</a></li>
<li class="chapter" data-level="18.1.5" data-path="multiple-linear.html"><a href="multiple-linear.html#staff_reg"><i class="fa fa-check"></i><b>18.1.5</b> Доработка модели</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="multiple-linear.html"><a href="multiple-linear.html#множественная-линейная-регрессия-с-количественными-и-категориальными-предикторами"><i class="fa fa-check"></i><b>18.2</b> Множественная линейная регрессия с количественными и категориальными предикторами</a><ul>
<li class="chapter" data-level="18.2.1" data-path="multiple-linear.html"><a href="multiple-linear.html#математическая-модель-1"><i class="fa fa-check"></i><b>18.2.1</b> Математическая модель</a></li>
<li class="chapter" data-level="18.2.2" data-path="multiple-linear.html"><a href="multiple-linear.html#подбор-модели-1"><i class="fa fa-check"></i><b>18.2.2</b> Подбор модели</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="multiple-linear.html"><a href="multiple-linear.html#модели-со-взаимодействием-предикторов"><i class="fa fa-check"></i><b>18.3</b> Модели со взаимодействием предикторов</a><ul>
<li class="chapter" data-level="18.3.1" data-path="multiple-linear.html"><a href="multiple-linear.html#математическая-модель-2"><i class="fa fa-check"></i><b>18.3.1</b> Математическая модель</a></li>
<li class="chapter" data-level="18.3.2" data-path="multiple-linear.html"><a href="multiple-linear.html#подбор-модели-2"><i class="fa fa-check"></i><b>18.3.2</b> Подбор модели</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="multiple-linear.html"><a href="multiple-linear.html#сравнение-моделей"><i class="fa fa-check"></i><b>18.4</b> Сравнение моделей</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>19</b> Дисперсионный анализ</a><ul>
<li class="chapter" data-level="19.1" data-path="anova.html"><a href="anova.html#параметризация-индикаторов-и-параметризация-эффектов"><i class="fa fa-check"></i><b>19.1</b> Параметризация индикаторов и параметризация эффектов</a></li>
<li class="chapter" data-level="19.2" data-path="anova.html"><a href="anova.html#однофакторный-дисперсионный-анализ"><i class="fa fa-check"></i><b>19.2</b> Однофакторный дисперсионный анализ</a><ul>
<li class="chapter" data-level="19.2.1" data-path="anova.html"><a href="anova.html#зачем-вообще-дисперсионный-анализ"><i class="fa fa-check"></i><b>19.2.1</b> Зачем вообще дисперсионный анализ?</a></li>
<li class="chapter" data-level="19.2.2" data-path="anova.html"><a href="anova.html#структура-изменчивости"><i class="fa fa-check"></i><b>19.2.2</b> Структура изменчивости</a></li>
<li class="chapter" data-level="19.2.3" data-path="anova.html"><a href="anova.html#тестирование-значимости-фактора"><i class="fa fa-check"></i><b>19.2.3</b> Тестирование значимости фактора</a></li>
<li class="chapter" data-level="19.2.4" data-path="anova.html"><a href="anova.html#дисперсионный-анализ-в-r"><i class="fa fa-check"></i><b>19.2.4</b> Дисперсионный анализ в R</a></li>
<li class="chapter" data-level="19.2.5" data-path="anova.html"><a href="anova.html#post-hoc-тесты"><i class="fa fa-check"></i><b>19.2.5</b> Post hoc тесты</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="anova.html"><a href="anova.html#многофакторный-дисперсионный-анализ"><i class="fa fa-check"></i><b>19.3</b> Многофакторный дисперсионный анализ</a><ul>
<li class="chapter" data-level="19.3.1" data-path="anova.html"><a href="anova.html#типы-сумм-квадратов"><i class="fa fa-check"></i><b>19.3.1</b> Типы сумм квадратов</a></li>
<li class="chapter" data-level="19.3.2" data-path="anova.html"><a href="anova.html#post-hoc-тесты-1"><i class="fa fa-check"></i><b>19.3.2</b> Post hoc тесты</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="anova.html"><a href="anova.html#дисперсионный-анализ-с-повторными-измерениями"><i class="fa fa-check"></i><b>19.4</b> Дисперсионный анализ с повторными измерениями</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>20</b> Ковариационный анализ</a><ul>
<li class="chapter" data-level="20.1" data-path="ancova.html"><a href="ancova.html#модель-ковариационного-анализа"><i class="fa fa-check"></i><b>20.1</b> Модель ковариационного анализа</a></li>
<li class="chapter" data-level="20.2" data-path="ancova.html"><a href="ancova.html#влияние-ковариаты"><i class="fa fa-check"></i><b>20.2</b> Влияние ковариаты</a></li>
<li class="chapter" data-level="20.3" data-path="ancova.html"><a href="ancova.html#более-сложные-модели"><i class="fa fa-check"></i><b>20.3</b> Более сложные модели</a></li>
<li class="chapter" data-level="20.4" data-path="ancova.html"><a href="ancova.html#тестирование-значимости-предикторов-и-диагностика-модели"><i class="fa fa-check"></i><b>20.4</b> Тестирование значимости предикторов и диагностика модели</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="logistic.html"><a href="logistic.html"><i class="fa fa-check"></i><b>21</b> Обобщенные линейные модели. Логистическая регрессия</a><ul>
<li class="chapter" data-level="21.1" data-path="logistic.html"><a href="logistic.html#ограничения-общих-линейных-моделей"><i class="fa fa-check"></i><b>21.1</b> Ограничения общих линейных моделей</a></li>
<li class="chapter" data-level="21.2" data-path="logistic.html"><a href="logistic.html#биномиальное-распределение"><i class="fa fa-check"></i><b>21.2</b> Биномиальное распределение</a></li>
<li class="chapter" data-level="21.3" data-path="logistic.html"><a href="logistic.html#бинарные-переменные"><i class="fa fa-check"></i><b>21.3</b> Бинарные переменные</a></li>
<li class="chapter" data-level="21.4" data-path="logistic.html"><a href="logistic.html#hr-данные"><i class="fa fa-check"></i><b>21.4</b> HR-данные</a></li>
<li class="chapter" data-level="21.5" data-path="logistic.html"><a href="logistic.html#задача-построения-линейной-модели"><i class="fa fa-check"></i><b>21.5</b> Задача построения линейной модели</a></li>
<li class="chapter" data-level="21.6" data-path="logistic.html"><a href="logistic.html#переход-от-дискретной-величины-к-непрерывной"><i class="fa fa-check"></i><b>21.6</b> Переход от дискретной величины к непрерывной</a><ul>
<li class="chapter" data-level="21.6.1" data-path="logistic.html"><a href="logistic.html#логистическая-кривая"><i class="fa fa-check"></i><b>21.6.1</b> Логистическая кривая</a></li>
<li class="chapter" data-level="21.6.2" data-path="logistic.html"><a href="logistic.html#шансы-и-логиты"><i class="fa fa-check"></i><b>21.6.2</b> Шансы и логиты</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="logistic.html"><a href="logistic.html#формулирование-модели-в-математическом-виде"><i class="fa fa-check"></i><b>21.7</b> Формулирование модели в математическом виде</a></li>
<li class="chapter" data-level="21.8" data-path="logistic.html"><a href="logistic.html#подбор-линейной-модели"><i class="fa fa-check"></i><b>21.8</b> Подбор линейной модели</a><ul>
<li class="chapter" data-level="21.8.1" data-path="logistic.html"><a href="logistic.html#метод-максимального-правдоподобия"><i class="fa fa-check"></i><b>21.8.1</b> Метод максимального правдоподобия</a></li>
</ul></li>
<li class="chapter" data-level="21.9" data-path="logistic.html"><a href="logistic.html#анализ-модели"><i class="fa fa-check"></i><b>21.9</b> Анализ модели</a></li>
<li class="chapter" data-level="21.10" data-path="logistic.html"><a href="logistic.html#анализ-девиансы-и-упрощение-модели"><i class="fa fa-check"></i><b>21.10</b> Анализ девиансы и упрощение модели</a></li>
<li class="chapter" data-level="21.11" data-path="logistic.html"><a href="logistic.html#интерпретация-коэффициентов-модели"><i class="fa fa-check"></i><b>21.11</b> Интерпретация коэффициентов модели</a><ul>
<li class="chapter" data-level="21.11.1" data-path="logistic.html"><a href="logistic.html#немного-алгебры-для-понимания-сути-коэффициентов"><i class="fa fa-check"></i><b>21.11.1</b> Немного алгебры для понимания сути коэффициентов</a></li>
</ul></li>
<li class="chapter" data-level="21.12" data-path="logistic.html"><a href="logistic.html#предсказательная-сила-модели"><i class="fa fa-check"></i><b>21.12</b> Предсказательная сила модели</a><ul>
<li class="chapter" data-level="21.12.1" data-path="logistic.html"><a href="logistic.html#перевод-непрерывных-предсказаний-в-дискретные"><i class="fa fa-check"></i><b>21.12.1</b> Перевод непрерывных предсказаний в дискретные</a></li>
<li class="chapter" data-level="21.12.2" data-path="logistic.html"><a href="logistic.html#confusion-matrix"><i class="fa fa-check"></i><b>21.12.2</b> Confusion matrix</a></li>
<li class="chapter" data-level="21.12.3" data-path="logistic.html"><a href="logistic.html#accuracy"><i class="fa fa-check"></i><b>21.12.3</b> Accuracy</a></li>
<li class="chapter" data-level="21.12.4" data-path="logistic.html"><a href="logistic.html#precision-and-recall"><i class="fa fa-check"></i><b>21.12.4</b> Precision and Recall</a></li>
<li class="chapter" data-level="21.12.5" data-path="logistic.html"><a href="logistic.html#f1-мера"><i class="fa fa-check"></i><b>21.12.5</b> F1-мера</a></li>
<li class="chapter" data-level="21.12.6" data-path="logistic.html"><a href="logistic.html#roc-auc"><i class="fa fa-check"></i><b>21.12.6</b> ROC-AUC</a></li>
</ul></li>
<li class="chapter" data-level="21.13" data-path="logistic.html"><a href="logistic.html#предсказания-на-новых-данных"><i class="fa fa-check"></i><b>21.13</b> Предсказания на новых данных</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="poisson.html"><a href="poisson.html"><i class="fa fa-check"></i><b>22</b> Пуассоновская регрессия</a><ul>
<li class="chapter" data-level="22.1" data-path="poisson.html"><a href="poisson.html#распределение-пуассона"><i class="fa fa-check"></i><b>22.1</b> Распределение Пуассона</a></li>
<li class="chapter" data-level="22.2" data-path="poisson.html"><a href="poisson.html#почему-обычные-регрессионные-модели-плохо-работают-на-счётных-данных"><i class="fa fa-check"></i><b>22.2</b> Почему обычные регрессионные модели плохо работают на счётных данных</a></li>
<li class="chapter" data-level="22.3" data-path="poisson.html"><a href="poisson.html#данные-1"><i class="fa fa-check"></i><b>22.3</b> Данные</a></li>
<li class="chapter" data-level="22.4" data-path="poisson.html"><a href="poisson.html#glm-с-пуассоновским-распределением-целевой-переменной"><i class="fa fa-check"></i><b>22.4</b> GLM с пуассоновским распределением целевой переменной</a><ul>
<li class="chapter" data-level="22.4.1" data-path="poisson.html"><a href="poisson.html#подбор-модели-в-r"><i class="fa fa-check"></i><b>22.4.1</b> Подбор модели в R</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="poisson.html"><a href="poisson.html#интерпретация-коэффициентов-модели-1"><i class="fa fa-check"></i><b>22.5</b> Интерпретация коэффициентов модели</a></li>
<li class="chapter" data-level="22.6" data-path="poisson.html"><a href="poisson.html#анализ-девиансы"><i class="fa fa-check"></i><b>22.6</b> Анализ девиансы</a></li>
<li class="chapter" data-level="22.7" data-path="poisson.html"><a href="poisson.html#проверка-на-сверхдисперсию-overdispersion"><i class="fa fa-check"></i><b>22.7</b> Проверка на сверхдисперсию (overdispersion)</a></li>
<li class="chapter" data-level="22.8" data-path="poisson.html"><a href="poisson.html#квазипуассоновские-модели"><i class="fa fa-check"></i><b>22.8</b> Квазипуассоновские модели</a><ul>
<li class="chapter" data-level="22.8.1" data-path="poisson.html"><a href="poisson.html#квазипуассоновские-модели-в-r"><i class="fa fa-check"></i><b>22.8.1</b> Квазипуассоновские модели в R</a></li>
</ul></li>
<li class="chapter" data-level="22.9" data-path="poisson.html"><a href="poisson.html#особенности-работы-с-квазипуассоновскими-моделями"><i class="fa fa-check"></i><b>22.9</b> Особенности работы с квазипуассоновскими моделями</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="regularization.html"><a href="regularization.html"><i class="fa fa-check"></i><b>23</b> Регуляризация регрессии</a><ul>
<li class="chapter" data-level="23.1" data-path="regularization.html"><a href="regularization.html#варианты-штрафа"><i class="fa fa-check"></i><b>23.1</b> Варианты штрафа</a><ul>
<li class="chapter" data-level="23.1.1" data-path="regularization.html"><a href="regularization.html#пример-работы-штрафного-коэффициента"><i class="fa fa-check"></i><b>23.1.1</b> Пример работы штрафного коэффициента</a></li>
</ul></li>
<li class="chapter" data-level="23.2" data-path="regularization.html"><a href="regularization.html#регуляризованная-регрессия-в-r"><i class="fa fa-check"></i><b>23.2</b> Регуляризованная регрессия в R</a><ul>
<li class="chapter" data-level="23.2.1" data-path="regularization.html"><a href="regularization.html#данные-2"><i class="fa fa-check"></i><b>23.2.1</b> Данные</a></li>
<li class="chapter" data-level="23.2.2" data-path="regularization.html"><a href="regularization.html#особенности-синтаксиса-пакета-glmnet"><i class="fa fa-check"></i><b>23.2.2</b> Особенности синтаксиса пакета <code>glmnet</code></a></li>
<li class="chapter" data-level="23.2.3" data-path="regularization.html"><a href="regularization.html#ridge-регрессия-в-r"><i class="fa fa-check"></i><b>23.2.3</b> Ridge-регрессия в R</a></li>
<li class="chapter" data-level="23.2.4" data-path="regularization.html"><a href="regularization.html#lasso-регрессия-в-r"><i class="fa fa-check"></i><b>23.2.4</b> LASSO-регрессия в R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="24" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>24</b> Смешанные линейные модели</a><ul>
<li class="chapter" data-level="24.1" data-path="glmm.html"><a href="glmm.html#ограничения-изученных-ранее-линейных-моделей"><i class="fa fa-check"></i><b>24.1</b> Ограничения изученных ранее линейных моделей</a></li>
<li class="chapter" data-level="24.2" data-path="glmm.html"><a href="glmm.html#случайные-vs-фиксированные-факторы"><i class="fa fa-check"></i><b>24.2</b> Случайные vs фиксированные факторы</a></li>
<li class="chapter" data-level="24.3" data-path="glmm.html"><a href="glmm.html#почему-обычные-методы-плохо-работают"><i class="fa fa-check"></i><b>24.3</b> Почему обычные методы плохо работают?</a><ul>
<li class="chapter" data-level="24.3.1" data-path="glmm.html"><a href="glmm.html#плохое-решение-игнорирование-группирующего-фактора"><i class="fa fa-check"></i><b>24.3.1</b> Плохое решение: игнорирование группирующего фактора</a></li>
<li class="chapter" data-level="24.3.2" data-path="glmm.html"><a href="glmm.html#плохое-решение-включение-группирующего-фактора-как-фиксированного"><i class="fa fa-check"></i><b>24.3.2</b> Плохое решение: включение группирующего фактора как фиксированного</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="glmm.html"><a href="glmm.html#виды-glmm-и-их-математическая-формулировка"><i class="fa fa-check"></i><b>24.4</b> Виды GLMM и их математическая формулировка</a><ul>
<li class="chapter" data-level="24.4.1" data-path="glmm.html"><a href="glmm.html#математическая-формулировка-модели-со-случайным-интерсептом"><i class="fa fa-check"></i><b>24.4.1</b> Математическая формулировка модели со случайным интерсептом</a></li>
<li class="chapter" data-level="24.4.2" data-path="glmm.html"><a href="glmm.html#математическая-формулировка-модели-со-случайными-интерсептом-и-углом-наклона"><i class="fa fa-check"></i><b>24.4.2</b> Математическая формулировка модели со случайными интерсептом и углом наклона</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="glmm.html"><a href="glmm.html#подбор-моделей-со-смешанными-эффектами"><i class="fa fa-check"></i><b>24.5</b> Подбор моделей со смешанными эффектами</a></li>
<li class="chapter" data-level="24.6" data-path="glmm.html"><a href="glmm.html#методы-подбора-параметров-в-смешанных-моделях"><i class="fa fa-check"></i><b>24.6</b> Методы подбора параметров в смешанных моделях</a><ul>
<li class="chapter" data-level="24.6.1" data-path="glmm.html"><a href="glmm.html#reml-или-ml"><i class="fa fa-check"></i><b>24.6.1</b> REML или ML?</a></li>
</ul></li>
<li class="chapter" data-level="24.7" data-path="glmm.html"><a href="glmm.html#диагностика-модели-2"><i class="fa fa-check"></i><b>24.7</b> Диагностика модели</a><ul>
<li class="chapter" data-level="24.7.1" data-path="glmm.html"><a href="glmm.html#индуцированные-корреляции"><i class="fa fa-check"></i><b>24.7.1</b> Индуцированные корреляции</a></li>
<li class="chapter" data-level="24.7.2" data-path="glmm.html"><a href="glmm.html#анализ-остатков-модели"><i class="fa fa-check"></i><b>24.7.2</b> Анализ остатков модели</a></li>
</ul></li>
<li class="chapter" data-level="24.8" data-path="glmm.html"><a href="glmm.html#предсказания-с-помощью-моделей.-сравнение-точности-предсказаний-смешанных-и-обычных-моделей"><i class="fa fa-check"></i><b>24.8</b> Предсказания с помощью моделей. Сравнение точности предсказаний смешанных и обычных моделей</a></li>
<li class="chapter" data-level="24.9" data-path="glmm.html"><a href="glmm.html#тестирование-гипотез"><i class="fa fa-check"></i><b>24.9</b> Тестирование гипотез</a><ul>
<li class="chapter" data-level="24.9.1" data-path="glmm.html"><a href="glmm.html#t-тест-вальда"><i class="fa fa-check"></i><b>24.9.1</b> t-тест Вальда</a></li>
<li class="chapter" data-level="24.9.2" data-path="glmm.html"><a href="glmm.html#тест-отношения-правдоподобий-likelihood-ratio-test-lrt"><i class="fa fa-check"></i><b>24.9.2</b> Тест отношения правдоподобий (likelihood ratio test, LRT)</a></li>
<li class="chapter" data-level="24.9.3" data-path="glmm.html"><a href="glmm.html#lrt-для-случайных-эффектов"><i class="fa fa-check"></i><b>24.9.3</b> LRT для случайных эффектов</a></li>
<li class="chapter" data-level="24.9.4" data-path="glmm.html"><a href="glmm.html#lrt-для-фиксированных-эффектов"><i class="fa fa-check"></i><b>24.9.4</b> LRT для фиксированных эффектов</a></li>
</ul></li>
<li class="chapter" data-level="24.10" data-path="glmm.html"><a href="glmm.html#сравнение-моделей-с-помощью-aic"><i class="fa fa-check"></i><b>24.10</b> Сравнение моделей с помощью AIC</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="cluster.html"><a href="cluster.html"><i class="fa fa-check"></i><b>25</b> Кластерный анализ</a><ul>
<li class="chapter" data-level="25.1" data-path="cluster.html"><a href="cluster.html#кластерный-анализ"><i class="fa fa-check"></i><b>25.1</b> Кластерный анализ</a></li>
<li class="chapter" data-level="25.2" data-path="cluster.html"><a href="cluster.html#геометрическая-интерпретация-задачи-кластеризации"><i class="fa fa-check"></i><b>25.2</b> Геометрическая интерпретация задачи кластеризации</a><ul>
<li class="chapter" data-level="25.2.1" data-path="cluster.html"><a href="cluster.html#проблема-кластеризации"><i class="fa fa-check"></i><b>25.2.1</b> Проблема кластеризации</a></li>
<li class="chapter" data-level="25.2.2" data-path="cluster.html"><a href="cluster.html#расстояние-между-объектами"><i class="fa fa-check"></i><b>25.2.2</b> Расстояние между объектами</a></li>
<li class="chapter" data-level="25.2.3" data-path="cluster.html"><a href="cluster.html#проблема-операционализации-расстояния"><i class="fa fa-check"></i><b>25.2.3</b> Проблема операционализации расстояния</a></li>
<li class="chapter" data-level="25.2.4" data-path="cluster.html"><a href="cluster.html#субъективность-кластерного-анализа"><i class="fa fa-check"></i><b>25.2.4</b> Субъективность кластерного анализа</a></li>
</ul></li>
<li class="chapter" data-level="25.3" data-path="cluster.html"><a href="cluster.html#расстояние-между-кластерами"><i class="fa fa-check"></i><b>25.3</b> Расстояние между кластерами</a><ul>
<li class="chapter" data-level="25.3.1" data-path="cluster.html"><a href="cluster.html#среднее-невзвешенное-расстояние"><i class="fa fa-check"></i><b>25.3.1</b> Среднее невзвешенное расстояние</a></li>
<li class="chapter" data-level="25.3.2" data-path="cluster.html"><a href="cluster.html#центроидный-метод"><i class="fa fa-check"></i><b>25.3.2</b> Центроидный метод</a></li>
<li class="chapter" data-level="25.3.3" data-path="cluster.html"><a href="cluster.html#метод-дальнего-соседа"><i class="fa fa-check"></i><b>25.3.3</b> Метод дальнего соседа</a></li>
<li class="chapter" data-level="25.3.4" data-path="cluster.html"><a href="cluster.html#метод-ближайшего-соседа"><i class="fa fa-check"></i><b>25.3.4</b> Метод ближайшего соседа</a></li>
<li class="chapter" data-level="25.3.5" data-path="cluster.html"><a href="cluster.html#расстояние-sørensendice"><i class="fa fa-check"></i><b>25.3.5</b> Расстояние Sørensen—Dice</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="cluster.html"><a href="cluster.html#иерархическая-кластеризация"><i class="fa fa-check"></i><b>25.4</b> Иерархическая кластеризация</a><ul>
<li class="chapter" data-level="25.4.1" data-path="cluster.html"><a href="cluster.html#алгоритм-иерархического-кластерного-анализа"><i class="fa fa-check"></i><b>25.4.1</b> Алгоритм иерархического кластерного анализа</a></li>
<li class="chapter" data-level="25.4.2" data-path="cluster.html"><a href="cluster.html#дендрограмма"><i class="fa fa-check"></i><b>25.4.2</b> Дендрограмма</a></li>
<li class="chapter" data-level="25.4.3" data-path="cluster.html"><a href="cluster.html#каменистая-осыпь"><i class="fa fa-check"></i><b>25.4.3</b> Каменистая осыпь</a></li>
<li class="chapter" data-level="25.4.4" data-path="cluster.html"><a href="cluster.html#когда-кластеризации-нет"><i class="fa fa-check"></i><b>25.4.4</b> Когда кластеризации нет?</a></li>
<li class="chapter" data-level="25.4.5" data-path="cluster.html"><a href="cluster.html#иерархическая-кластеризация-в-r"><i class="fa fa-check"></i><b>25.4.5</b> Иерархическая кластеризация в R</a></li>
<li class="chapter" data-level="25.4.6" data-path="cluster.html"><a href="cluster.html#чем-плох-иерархический-кластерный-анализ"><i class="fa fa-check"></i><b>25.4.6</b> Чем плох иерархический кластерный анализ?</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="cluster.html"><a href="cluster.html#k-means-метод-k-средних"><i class="fa fa-check"></i><b>25.5</b> k-means (метод k-средних)</a><ul>
<li class="chapter" data-level="25.5.1" data-path="cluster.html"><a href="cluster.html#алгоритм-метода-k-средних"><i class="fa fa-check"></i><b>25.5.1</b> Алгоритм метода k-средних</a></li>
<li class="chapter" data-level="25.5.2" data-path="cluster.html"><a href="cluster.html#ограничения-k-means"><i class="fa fa-check"></i><b>25.5.2</b> Ограничения k-means</a></li>
<li class="chapter" data-level="25.5.3" data-path="cluster.html"><a href="cluster.html#начальное-положение-кластеров"><i class="fa fa-check"></i><b>25.5.3</b> Начальное положение кластеров</a></li>
<li class="chapter" data-level="25.5.4" data-path="cluster.html"><a href="cluster.html#k-means-в-r"><i class="fa fa-check"></i><b>25.5.4</b> k-means в R</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="cluster.html"><a href="cluster.html#метрики-качества-кластеризации"><i class="fa fa-check"></i><b>25.6</b> Метрики качества кластеризации</a><ul>
<li class="chapter" data-level="25.6.1" data-path="cluster.html"><a href="cluster.html#внешние-метрики"><i class="fa fa-check"></i><b>25.6.1</b> Внешние метрики</a></li>
<li class="chapter" data-level="25.6.2" data-path="cluster.html"><a href="cluster.html#внутренние-метрики"><i class="fa fa-check"></i><b>25.6.2</b> Внутренние метрики</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>26</b> Анализ главных компонент</a><ul>
<li class="chapter" data-level="26.1" data-path="pca.html"><a href="pca.html#проклятие-размерности-curse-of-dimensionality"><i class="fa fa-check"></i><b>26.1</b> Проклятие размерности (curse of dimensionality)</a><ul>
<li class="chapter" data-level="26.1.1" data-path="pca.html"><a href="pca.html#геометрическая-вероятность"><i class="fa fa-check"></i><b>26.1.1</b> Геометрическая вероятность</a></li>
</ul></li>
<li class="chapter" data-level="26.2" data-path="pca.html"><a href="pca.html#факторный-анализ-vs-анализ-главных-компонент"><i class="fa fa-check"></i><b>26.2</b> Факторный анализ vs анализ главных компонент</a></li>
<li class="chapter" data-level="26.3" data-path="pca.html"><a href="pca.html#задачи-факторного-анализа-и-анализа-главных-компонент"><i class="fa fa-check"></i><b>26.3</b> Задачи факторного анализа и анализа главных компонент</a></li>
<li class="chapter" data-level="26.4" data-path="pca.html"><a href="pca.html#математическая-модель-анализа-главных-компонент"><i class="fa fa-check"></i><b>26.4</b> Математическая модель анализа главных компонент</a></li>
<li class="chapter" data-level="26.5" data-path="pca.html"><a href="pca.html#сокращение-размерности-признакового-пространства"><i class="fa fa-check"></i><b>26.5</b> Сокращение размерности признакового пространства</a></li>
<li class="chapter" data-level="26.6" data-path="pca.html"><a href="pca.html#реализация-pca-в-r"><i class="fa fa-check"></i><b>26.6</b> Реализация PCA в R</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="efa.html"><a href="efa.html"><i class="fa fa-check"></i><b>27</b> Эксплораторный факторный анализ</a><ul>
<li class="chapter" data-level="27.1" data-path="efa.html"><a href="efa.html#математическая-модель-эскплораторного-факторного-анализа"><i class="fa fa-check"></i><b>27.1</b> Математическая модель эскплораторного факторного анализа</a><ul>
<li class="chapter" data-level="27.1.1" data-path="efa.html"><a href="efa.html#вращение-факторов-factor-rotation"><i class="fa fa-check"></i><b>27.1.1</b> Вращение факторов (factor rotation)</a></li>
</ul></li>
<li class="chapter" data-level="27.2" data-path="efa.html"><a href="efa.html#реализация-efa-в-r"><i class="fa fa-check"></i><b>27.2</b> Реализация EFA в R</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="cfa.html"><a href="cfa.html"><i class="fa fa-check"></i><b>28</b> Конфирматорный факторный анализ</a><ul>
<li class="chapter" data-level="28.1" data-path="cfa.html"><a href="cfa.html#экспресс-введение-в-структурное-моделирование"><i class="fa fa-check"></i><b>28.1</b> Экспресс-введение в структурное моделирование</a><ul>
<li class="chapter" data-level="28.1.1" data-path="cfa.html"><a href="cfa.html#how_much_data"><i class="fa fa-check"></i><b>28.1.1</b> Сколько нужно данных?</a></li>
</ul></li>
<li class="chapter" data-level="28.2" data-path="cfa.html"><a href="cfa.html#модель-конфирматорного-факторного-анализа"><i class="fa fa-check"></i><b>28.2</b> Модель конфирматорного факторного анализа</a></li>
<li class="chapter" data-level="28.3" data-path="cfa.html"><a href="cfa.html#cfa-в-r"><i class="fa fa-check"></i><b>28.3</b> CFA в R</a><ul>
<li class="chapter" data-level="28.3.1" data-path="cfa.html"><a href="cfa.html#данные-4"><i class="fa fa-check"></i><b>28.3.1</b> Данные</a></li>
<li class="chapter" data-level="28.3.2" data-path="cfa.html"><a href="cfa.html#синтаксис-пакета-lavaan"><i class="fa fa-check"></i><b>28.3.2</b> Синтаксис пакета <code>lavaan</code></a></li>
<li class="chapter" data-level="28.3.3" data-path="cfa.html"><a href="cfa.html#подбор-модели-3"><i class="fa fa-check"></i><b>28.3.3</b> Подбор модели</a></li>
<li class="chapter" data-level="28.3.4" data-path="cfa.html"><a href="cfa.html#оценка-качества-модели-1"><i class="fa fa-check"></i><b>28.3.4</b> Оценка качества модели</a></li>
<li class="chapter" data-level="28.3.5" data-path="cfa.html"><a href="cfa.html#визуализация-результатов"><i class="fa fa-check"></i><b>28.3.5</b> Визуализация результатов</a></li>
<li class="chapter" data-level="28.3.6" data-path="cfa.html"><a href="cfa.html#модификация-модели"><i class="fa fa-check"></i><b>28.3.6</b> Модификация модели</a></li>
<li class="chapter" data-level="28.3.7" data-path="cfa.html"><a href="cfa.html#сравнение-моделей-1"><i class="fa fa-check"></i><b>28.3.7</b> Сравнение моделей</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="29" data-path="further.html"><a href="further.html"><i class="fa fa-check"></i><b>29</b> Что дальше?</a><ul>
<li class="chapter" data-level="29.1" data-path="further.html"><a href="further.html#углубляемся-в-r"><i class="fa fa-check"></i><b>29.1</b> Углубляемся в R</a></li>
<li class="chapter" data-level="29.2" data-path="further.html"><a href="further.html#тонем-в-математике"><i class="fa fa-check"></i><b>29.2</b> Тонем в математике</a></li>
<li class="chapter" data-level="29.3" data-path="further.html"><a href="further.html#ныряем-в-статистику"><i class="fa fa-check"></i><b>29.3</b> Ныряем в статистику</a></li>
<li class="chapter" data-level="29.4" data-path="further.html"><a href="further.html#бороздим-просторы-анализа-данных"><i class="fa fa-check"></i><b>29.4</b> Бороздим просторы анализа данных</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>Литература</a><ul>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html#касаемо-математики"><i class="fa fa-check"></i>Касаемо математики</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html#относительно-статистики"><i class="fa fa-check"></i>Относительно статистики</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html#about-r"><i class="fa fa-check"></i>About R</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html#во-славу-андана"><i class="fa fa-check"></i>Во славу андана</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">HSE UX LAB | Анализ данных + R: мир линейных моделей | Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cfa" class="section level1">
<h1><span class="header-section-number">28</span> Конфирматорный факторный анализ</h1>
<div id="экспресс-введение-в-структурное-моделирование" class="section level2">
<h2><span class="header-section-number">28.1</span> Экспресс-введение в структурное моделирование</h2>
<center>
<img src="img/cfa_meme1.png">
</center>
<p>Вспомним, кто мы… Мы же с вами исследователи из области социальных и/или гуманитарных наук. А чем мы богаты? Теоретическими моделями, на которых мы основываем наши исследования! А какая теоретическая модель хороша? Та, которая получила эмпирическое подтверждение!<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>А как это?…</p>
<p>В предыдущей главе мы научились искать, факторы, скрытые за наблюдаемыми переменными — это уже большой шаг. Однако недостаточный. И главное ограничение PCA и EFA — это то, что мы ищем независимые факторы/главные компоненты, в то время как структура взаимосвязей между латентными переменными может быть гораздо сложнее. Кроме того, эти скрытые переменные могут предсказывать другие наблюдаемые переменные: например, уровень вовлеченности сотрудников [возможно] будет предсказывать выполнение KPI, что в свою очередь предсказывает заработную плату. То есть в данным случае мы движемся не от наблюдаемых переменных к латентным, а в обратном направлении. А ведь влияние одних латентных конструктов могут быть опосредованы другими… И в итоге получается что-то такое:</p>
<center>
<img src="img/sem_scheme.png">
</center>
<p>Короче, модель может быть сколь угодно сложна — и надо её каким-то образом эмпирически проверять. Это позволяют делать <strong>методы структурного моделирования (structural equation modelling, SEM)</strong>.</p>
<p>Что это за методы? Это группа методов, которые проверять модели (гипотезы), описывающие наши данные. Проверка состоит из двух больших шагов:</p>
<ul>
<li>задание теоретической модели генерации данных;</li>
<li>проверка того, насколько предложенная модель хорошо подходит под наши данные.</li>
</ul>
<p>Но, если вдуматься, то так работают все статистические методы — даже в линейной регрессии мы сначала задаём линейную модель, а потом проверяем, насколько хорошо она описывает взаимосвязи, представленные в данных. В чем же особенность SEM?</p>
<p>Во-первых, в модель включаются <em>латентные переменные</em> — мы получаем возможность их моделировать и использовать для предсказаний. Этого не может делать, например, хорошо знакомая нам линейная регрессия, так как она работает только с наблюдаемыми переменными.</p>
<p>Во-вторых, в модель могут быть включены <em>косвенные связи</em> — связи между латентными переменными. То есть мы можем моделировать связи между переменными, которые мы даже не можем измерить! Ну, круто же!</p>
<p>Кроме того, модели удобно визуализируются с помощью диаграмм, аналогично рисунку выше.</p>
<div id="how_much_data" class="section level3">
<h3><span class="header-section-number">28.1.1</span> Сколько нужно данных?</h3>
<p>Есть мнение, что «структурное моделирование требует большого количества данных». Не очень понятно, что считать большим количеством, однако эвристика следующая: <em>на один оцениваемый параметр нужно не менее 10 наблюдений</em>. Выглядит как что-то приемлемое.</p>
</div>
</div>
<div id="модель-конфирматорного-факторного-анализа" class="section level2">
<h2><span class="header-section-number">28.2</span> Модель конфирматорного факторного анализа</h2>
<p>Окей, мы брифли взглянули на то, что такое структурное моделирование. Если мы возьмем от него только часть, то получим <strong>конфирматорный факторый анализ (confirmatory factor analysis)</strong>. Осталось понять, какую часть надо взять.</p>
<p>Наша задача — проверить факторный структуру данных, которую мы взяли из теории или нашли с помощью эксплораторного факторного анализа. То есть, в общем виде что-то такое:</p>
<center>
<img src="img/cfa_scheme.png">
</center>
<p>Выглядит уже не так страшно и запустанно.</p>
<p>Как это всё работает внутри? Сложно. Но, на самом деле, за всем стоит привычная нам множественная линейная регрессия и уже знакомый нам метод максимального правдоподобия, ведь мы всё ещё в рамках линейных моделей.</p>
<p>Чуть выше мы обсуждали, <a href="cfa.html#how_much_data">сколько нужно данных</a>, и сказали, что «10 наблюдений на один параметр». Однако тактично умолчали, что есть такое параметр. Так вот <em>параметры</em> — это, проще говоря, стрелочки на схеме выше. Это либо <em>факторный нагрузки</em>, так же как и в EFA, или <em>коэффициенты косвенных связей</em> между латентными переменными.</p>
<p>Конфирматорный факторный анализ в некотором смысле дополняет эксплораторный. Так, он позволяет уточнить и дополнить результаты последнего, а именно ответить на вопросы:</p>
<ul>
<li>пересекаются ли факторы? — действительно ли каждый переменная обусловлена влиянием одного фактора?</li>
<li>достоверны ли статистически факторные нагрузки?</li>
<li>как коррелируют сами факторы и как это влияет на факторные нагрузки?</li>
<li>отличается ли дисперсия фактора от нуля? — ведь если нет, тогда этот фактор не информативен, то есть не дифференцирует респондентов</li>
</ul>
<p>Итак, модель конфирматорного факторного анализа мы осознали. Пора писать код!</p>
</div>
<div id="cfa-в-r" class="section level2">
<h2><span class="header-section-number">28.3</span> CFA в R</h2>
<div id="данные-4" class="section level3">
<h3><span class="header-section-number">28.3.1</span> Данные</h3>
<p>Сегодня работаем с данными по адаптации психометрической методики, направленной на измерении толерантности к неопределенности. Загрузим их, а также подключим необходимые библиотеки:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="cfa.html#cb1-1"></a><span class="kw">library</span>(tidyverse) <span class="co"># наш любимый</span></span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.4     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="cfa.html#cb5-1"></a><span class="kw">library</span>(lavaan) <span class="co"># для структурного моделирования</span></span></code></pre></div>
<pre><code>## This is lavaan 0.6-8
## lavaan is FREE software! Please report any bugs.</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="cfa.html#cb7-1"></a><span class="kw">library</span>(semPlot) <span class="co"># для визуализаций </span></span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="cfa.html#cb8-1"></a>tolunc &lt;-<span class="st"> </span><span class="kw">read_csv2</span>(<span class="st">&#39;https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/tolerance_uncertainty.csv&#39;</span>)</span></code></pre></div>
<pre><code>## ℹ Using &#39;,&#39; as decimal and &#39;.&#39; as grouping mark. Use `read_delim()` for more control.</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   sex = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="cfa.html#cb11-1"></a><span class="kw">str</span>(tolunc)</span></code></pre></div>
<pre><code>## tibble [405 × 24] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ sex : chr [1:405] &quot;женский&quot; &quot;женский&quot; &quot;мужской&quot; &quot;мужской&quot; ...
##  $ age : num [1:405] 20 18 22 20 18 18 18 20 21 18 ...
##  $ tu1 : num [1:405] 6 1 3 4 1 4 4 6 1 1 ...
##  $ tu2 : num [1:405] 3 1 5 6 4 6 3 6 1 4 ...
##  $ tu3 : num [1:405] 4 7 4 6 5 5 6 7 4 5 ...
##  $ tu4 : num [1:405] 5 4 6 6 5 7 5 6 1 7 ...
##  $ tu5 : num [1:405] 2 7 6 6 7 5 5 7 7 6 ...
##  $ tu6 : num [1:405] 7 1 4 6 1 5 5 7 1 1 ...
##  $ tu7 : num [1:405] 1 3 6 6 4 6 5 6 1 6 ...
##  $ tu8 : num [1:405] 5 3 4 6 2 4 2 7 3 3 ...
##  $ tu9 : num [1:405] 5 7 7 6 4 5 3 6 4 5 ...
##  $ tu10: num [1:405] 6 6 7 6 7 4 5 7 4 2 ...
##  $ tu11: num [1:405] 3 1 4 7 2 6 7 6 2 3 ...
##  $ tu12: num [1:405] 4 3 6 7 5 6 6 7 2 6 ...
##  $ tu13: num [1:405] 4 4 6 7 4 4 5 6 4 2 ...
##  $ tu14: num [1:405] 4 7 6 7 6 6 5 7 5 7 ...
##  $ tu15: num [1:405] 4 7 4 7 4 6 5 7 4 4 ...
##  $ tu16: num [1:405] 5 1 4 7 1 5 5 6 2 1 ...
##  $ tu17: num [1:405] 4 3 5 7 5 6 6 7 6 7 ...
##  $ tu18: num [1:405] 1 4 6 7 3 6 5 6 4 5 ...
##  $ tu19: num [1:405] 4 6 7 7 4 6 4 6 4 7 ...
##  $ tu20: num [1:405] 4 1 6 7 5 5 3 5 1 1 ...
##  $ tu21: num [1:405] 4 7 5 7 4 7 4 7 7 7 ...
##  $ tu22: num [1:405] 4 5 4 5 2 5 4 6 5 2 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   sex = col_character(),
##   ..   age = col_double(),
##   ..   tu1 = col_double(),
##   ..   tu2 = col_double(),
##   ..   tu3 = col_double(),
##   ..   tu4 = col_double(),
##   ..   tu5 = col_double(),
##   ..   tu6 = col_double(),
##   ..   tu7 = col_double(),
##   ..   tu8 = col_double(),
##   ..   tu9 = col_double(),
##   ..   tu10 = col_double(),
##   ..   tu11 = col_double(),
##   ..   tu12 = col_double(),
##   ..   tu13 = col_double(),
##   ..   tu14 = col_double(),
##   ..   tu15 = col_double(),
##   ..   tu16 = col_double(),
##   ..   tu17 = col_double(),
##   ..   tu18 = col_double(),
##   ..   tu19 = col_double(),
##   ..   tu20 = col_double(),
##   ..   tu21 = col_double(),
##   ..   tu22 = col_double()
##   .. )</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="cfa.html#cb13-1"></a><span class="kw">summary</span>(tolunc)</span></code></pre></div>
<pre><code>##      sex                 age             tu1             tu2      
##  Length:405         Min.   :17.00   Min.   :1.000   Min.   :1.00  
##  Class :character   1st Qu.:18.00   1st Qu.:2.000   1st Qu.:2.00  
##  Mode  :character   Median :19.00   Median :3.000   Median :3.00  
##                     Mean   :20.51   Mean   :3.343   Mean   :3.36  
##                     3rd Qu.:20.00   3rd Qu.:4.000   3rd Qu.:4.00  
##                     Max.   :68.00   Max.   :7.000   Max.   :7.00  
##       tu3             tu4             tu5             tu6       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:4.000   1st Qu.:3.000   1st Qu.:3.000  
##  Median :4.000   Median :5.000   Median :5.000   Median :4.000  
##  Mean   :3.835   Mean   :4.556   Mean   :4.528   Mean   :3.795  
##  3rd Qu.:5.000   3rd Qu.:6.000   3rd Qu.:6.000   3rd Qu.:5.000  
##  Max.   :7.000   Max.   :7.000   Max.   :7.000   Max.   :7.000  
##       tu7             tu8             tu9             tu10            tu11     
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.00  
##  1st Qu.:4.000   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:4.00  
##  Median :4.000   Median :4.000   Median :5.000   Median :4.000   Median :5.00  
##  Mean   :4.284   Mean   :3.748   Mean   :4.546   Mean   :4.415   Mean   :4.62  
##  3rd Qu.:5.000   3rd Qu.:5.000   3rd Qu.:6.000   3rd Qu.:6.000   3rd Qu.:6.00  
##  Max.   :7.000   Max.   :7.000   Max.   :7.000   Max.   :7.000   Max.   :7.00  
##       tu12            tu13            tu14            tu15      
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000  
##  Median :5.000   Median :4.000   Median :5.000   Median :5.000  
##  Mean   :4.523   Mean   :4.269   Mean   :4.585   Mean   :4.474  
##  3rd Qu.:6.000   3rd Qu.:5.000   3rd Qu.:6.000   3rd Qu.:5.000  
##  Max.   :7.000   Max.   :7.000   Max.   :7.000   Max.   :7.000  
##       tu16            tu17           tu18            tu19            tu20      
##  Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:2.000   1st Qu.:4.00   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.000  
##  Median :4.000   Median :5.00   Median :4.000   Median :5.000   Median :3.000  
##  Mean   :3.662   Mean   :4.57   Mean   :4.116   Mean   :4.533   Mean   :3.235  
##  3rd Qu.:5.000   3rd Qu.:6.00   3rd Qu.:5.000   3rd Qu.:6.000   3rd Qu.:4.000  
##  Max.   :7.000   Max.   :7.00   Max.   :7.000   Max.   :7.000   Max.   :7.000  
##       tu21            tu22      
##  Min.   :1.000   Min.   :1.000  
##  1st Qu.:5.000   1st Qu.:3.000  
##  Median :6.000   Median :4.000  
##  Mean   :5.472   Mean   :3.867  
##  3rd Qu.:7.000   3rd Qu.:5.000  
##  Max.   :7.000   Max.   :7.000</code></pre>
<p>Это одношкальная методика, поэтому все вопросы направлены на измерение одной латентной переменной — толерантности к неопределенности. Получается очень простая модель, которую необходимо проверить.</p>
</div>
<div id="синтаксис-пакета-lavaan" class="section level3">
<h3><span class="header-section-number">28.3.2</span> Синтаксис пакета <code>lavaan</code></h3>
<p>Однако первоначально нам надо освоиться с пакетом <code>lavaan</code> (<strong>la</strong>ten <strong>va</strong>rible <strong>an</strong>alysis). Это самый популярный пакет для структурного моделирования, однако у него несколько специфический синтаксис.</p>
<p>В теоретической модели могут присутствовать различные типы связей:</p>
<ul>
<li><strong>измерения</strong> — связи от наблюдаемых переменных к латентным (наблюдаемые → латентные)</li>
<li><strong>регрессии</strong> — связи от латентных переменны к наблюдаемым (латентные → наблюдаемые)</li>
<li>и <strong>корреляции</strong> — связи между наблюдаемыми и латентными переменными (наблюдаемые → наблюдаемые, латентные → латентные)</li>
</ul>
<p>Для того, чтобы записать такую структуру модели был придуман специальный «язык», а вернее, обозначения:</p>
<table>
<thead>
<tr class="header">
<th align="center">Измерения</th>
<th align="center">Регрессии</th>
<th align="center">Корреляции</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>=~</code></td>
<td align="center"><code>~</code></td>
<td align="center"><code>~~</code></td>
</tr>
</tbody>
</table>
<p>Для CFA нам необходимы только <em>измерения</em>, так как мы хотим проверить структуру измеритеьной факторной модели.</p>
<p>Модель в <code>lavaan</code> — это одна строка, которая передается в функцию. Далее функции сами парсят строку так, как им надо.</p>
<p>Наша модель будет записываться так:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="cfa.html#cb15-1"></a>mdl1 &lt;-<span class="st"> &quot;F1 =~ tu1 + tu2 + tu3 + tu4 + tu5 + tu6 + tu7 + tu8 + tu9 + tu10 + tu11 + tu12 + tu13 + tu14 + tu15 + tu16 + tu17 + tu18 + tu19 + tu20 + tu21 + tu22&quot;</span></span></code></pre></div>
<p>Теперь можно перейти к подбору модели.</p>
</div>
<div id="подбор-модели-3" class="section level3">
<h3><span class="header-section-number">28.3.3</span> Подбор модели</h3>
<p>Для конфирматорного факторного анализа в пакета <code>lavaan</code> предусмотрена функция <code>cfa()</code>, которая хочет на вход модель и данные. Попробуем:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="cfa.html#cb16-1"></a>model1 &lt;-<span class="st"> </span><span class="kw">cfa</span>(mdl1, <span class="dt">data =</span> tolunc)</span></code></pre></div>
<p>Модель сошлась, никаких ошибок и предупреждение нам не выдали. Хорошо.</p>
<p>Воспользуемся хорошо знакомой нам функцией <code>summary()</code>, чтобы посмотреть на результаты:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="cfa.html#cb17-1"></a><span class="kw">summary</span>(model1)</span></code></pre></div>
<pre><code>## lavaan 0.6-8 ended normally after 31 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        44
##                                                       
##   Number of observations                           405
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                              1401.716
##   Degrees of freedom                               209
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   F1 =~                                               
##     tu1               1.000                           
##     tu2               0.922    0.086   10.710    0.000
##     tu3               0.944    0.091   10.418    0.000
##     tu4               0.822    0.088    9.353    0.000
##     tu5               0.823    0.089    9.267    0.000
##     tu6               1.197    0.101   11.821    0.000
##     tu7               0.707    0.073    9.632    0.000
##     tu8               1.051    0.094   11.242    0.000
##     tu9               0.818    0.085    9.635    0.000
##     tu10              0.875    0.089    9.799    0.000
##     tu11              0.763    0.082    9.303    0.000
##     tu12              0.920    0.088   10.496    0.000
##     tu13              0.817    0.082    9.922    0.000
##     tu14              0.628    0.083    7.519    0.000
##     tu15              0.708    0.083    8.556    0.000
##     tu16              1.080    0.092   11.697    0.000
##     tu17              0.830    0.091    9.147    0.000
##     tu18              0.771    0.085    9.043    0.000
##     tu19              0.790    0.088    9.028    0.000
##     tu20              0.794    0.085    9.320    0.000
##     tu21              0.327    0.075    4.364    0.000
##     tu22              0.745    0.081    9.172    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .tu1               1.487    0.112   13.325    0.000
##    .tu2               1.330    0.099   13.370    0.000
##    .tu3               1.549    0.115   13.457    0.000
##    .tu4               1.707    0.125   13.698    0.000
##    .tu5               1.762    0.128   13.713    0.000
##    .tu6               1.447    0.112   12.895    0.000
##    .tu7               1.146    0.084   13.644    0.000
##    .tu8               1.413    0.107   13.176    0.000
##    .tu9               1.535    0.113   13.643    0.000
##    .tu10              1.659    0.122   13.609    0.000
##    .tu11              1.494    0.109   13.707    0.000
##    .tu12              1.431    0.107   13.435    0.000
##    .tu13              1.387    0.102   13.582    0.000
##    .tu14              1.869    0.134   13.947    0.000
##    .tu15              1.664    0.120   13.825    0.000
##    .tu16              1.241    0.096   12.963    0.000
##    .tu17              1.869    0.136   13.734    0.000
##    .tu18              1.670    0.121   13.751    0.000
##    .tu19              1.763    0.128   13.754    0.000
##    .tu20              1.613    0.118   13.704    0.000
##    .tu21              1.830    0.129   14.152    0.000
##    .tu22              1.493    0.109   13.730    0.000
##     F1                0.961    0.142    6.761    0.000</code></pre>
<p>Привет, стена текста. Что тут нам надо увидеть?</p>
<p>Во-первых, первая строка нам говорит о том, что модель сошлась и всё хорошо. Потребовалось для этого 31 итерация.</p>
<p>Далее на говорят, что был использован метод максимального правдопободия (ML), в нашей модели 44 параметра и она построена на 405 наблюдениях.</p>
<p>Во-вторых, нам рапортуются результаты теста <span class="math inline">\(\chi^2\)</span>, который тестирует гипотезу о соответствии данных теоретической модели. Как обычно, представлена сама статистика (1401.716), число степеней свободы (209) и p-value (&lt; .001). <em>Нулевая гипотеза данного теста: данные согласуются с теоретической моделью.</em> Соответственно, если мы получаем p-значение, меньшее конвенционального 0.05, то мы вынуждены отклонить нулевую гипотезу. То есть в данном случае результаты теста говорят о том, что данные не теоретическая модель не подстверждается данными. Однако делать выводы рано. На самом деле, использовать <span class="math inline">\(\chi^2\)</span> бесполезно, так как при большом количестве данных p-value будет всегда меньше 0.05, поэтому в статьях его часто даже не указывают, а качество модели оценивают по другим метрикам, к которым мы обратимся позднее.</p>
<p>Далее идёт таблица факторных нагрузок. Она очень похожа на регрессионную таблицу — и это неспроста. Это и есть те самые множественные регрессии, на которых строится математическая модель конфирматорного факторного анализа.</p>
<p>Здесь необходимо отметить один критичный момент: <em>очередность задания переменных в модели играет роль</em>. Процедура подбоора модели устроена так, что все переменные нормируются относительно первой, поэтому её коэффициент (нагрузка) равен единице. Собственно, по этой причине здесь возможны факторные нагрузки, большие единицы (что не встречается с EFA). Критичен этот момент ещё и с той точки зрения, что первой переменной в модели необходимо указывать ту, которая положительно связана с фактором, чтобы, номируясь относительно неё, другие переменные не меняли своего направления связи.</p>
<p>В общем случае далее будет идти таблица, описывающая связи между латентными переменными. Так как у нас один фактор в модели, то этой таблицы нет. Статистический вывод делается по стандартному алгоритму.</p>
<p>Последняя таблица — это дисперсии остатков и факторов. Здесь необходимо обратить внимание имено на лисперсию факторов и проверить, отличается ли она статистически от нуля. В нашем случае всё ок — дисперсия фактора значима, значит и сам фактор значим. Если же дисперсия статистически равна нулю, то существование данного фактора не нашло эмпирического подтверждения.</p>
<p>Можно выгрузить эти таблицы под отдельности:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="cfa.html#cb19-1"></a>sfit &lt;-<span class="st"> </span><span class="kw">standardizedsolution</span>(model1)</span></code></pre></div>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="cfa.html#cb20-1"></a><span class="co"># факторные нагрузки</span></span>
<span id="cb20-2"><a href="cfa.html#cb20-2"></a>sfit[sfit<span class="op">$</span>op <span class="op">==</span><span class="st"> &quot;=~&quot;</span>, ]</span></code></pre></div>
<pre><code>##    lhs op  rhs est.std    se      z pvalue ci.lower ci.upper
## 1   F1 =~  tu1   0.627 0.033 19.120      0    0.562    0.691
## 2   F1 =~  tu2   0.617 0.033 18.491      0    0.551    0.682
## 3   F1 =~  tu3   0.596 0.035 17.253      0    0.529    0.664
## 4   F1 =~  tu4   0.525 0.039 13.634      0    0.449    0.600
## 5   F1 =~  tu5   0.519 0.039 13.389      0    0.443    0.595
## 6   F1 =~  tu6   0.698 0.028 24.807      0    0.643    0.754
## 7   F1 =~  tu7   0.543 0.038 14.471      0    0.470    0.617
## 8   F1 =~  tu8   0.655 0.031 21.142      0    0.594    0.716
## 9   F1 =~  tu9   0.543 0.038 14.481      0    0.470    0.617
## 10  F1 =~ tu10   0.554 0.037 15.008      0    0.482    0.627
## 11  F1 =~ tu11   0.522 0.039 13.492      0    0.446    0.597
## 12  F1 =~ tu12   0.602 0.034 17.571      0    0.535    0.669
## 13  F1 =~ tu13   0.563 0.036 15.417      0    0.491    0.634
## 14  F1 =~ tu14   0.410 0.044  9.378      0    0.325    0.496
## 15  F1 =~ tu15   0.474 0.041 11.560      0    0.394    0.554
## 16  F1 =~ tu16   0.689 0.029 23.939      0    0.633    0.745
## 17  F1 =~ tu17   0.512 0.039 13.055      0    0.435    0.588
## 18  F1 =~ tu18   0.505 0.040 12.777      0    0.427    0.582
## 19  F1 =~ tu19   0.504 0.040 12.735      0    0.426    0.581
## 20  F1 =~ tu20   0.523 0.039 13.538      0    0.447    0.598
## 21  F1 =~ tu21   0.231 0.049  4.668      0    0.134    0.328
## 22  F1 =~ tu22   0.513 0.039 13.126      0    0.437    0.590</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="cfa.html#cb22-1"></a><span class="co"># корреляции</span></span>
<span id="cb22-2"><a href="cfa.html#cb22-2"></a><span class="co"># в нашем случае ничего не выводится, так как в модель не включены корреляции</span></span>
<span id="cb22-3"><a href="cfa.html#cb22-3"></a>sfit[sfit<span class="op">$</span>op <span class="op">==</span><span class="st"> &quot;~~&quot;</span> <span class="op">&amp;</span><span class="st"> </span>sfit<span class="op">$</span>lhs <span class="op">!=</span><span class="st"> </span>sfit<span class="op">$</span>rhs, ]</span></code></pre></div>
<pre><code>## [1] lhs      op       rhs      est.std  se       z        pvalue   ci.lower
## [9] ci.upper
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="cfa.html#cb24-1"></a><span class="co"># остатки</span></span>
<span id="cb24-2"><a href="cfa.html#cb24-2"></a>sfit[sfit<span class="op">$</span>op <span class="op">==</span><span class="st"> &quot;~~&quot;</span> <span class="op">&amp;</span><span class="st"> </span>sfit<span class="op">$</span>lhs <span class="op">==</span><span class="st"> </span>sfit<span class="op">$</span>rhs, ]</span></code></pre></div>
<pre><code>##     lhs op  rhs est.std    se      z pvalue ci.lower ci.upper
## 23  tu1 ~~  tu1   0.607 0.041 14.790      0    0.527    0.688
## 24  tu2 ~~  tu2   0.619 0.041 15.051      0    0.539    0.700
## 25  tu3 ~~  tu3   0.644 0.041 15.622      0    0.563    0.725
## 26  tu4 ~~  tu4   0.724 0.040 17.924      0    0.645    0.804
## 27  tu5 ~~  tu5   0.730 0.040 18.128      0    0.651    0.809
## 28  tu6 ~~  tu6   0.512 0.039 13.027      0    0.435    0.589
## 29  tu7 ~~  tu7   0.705 0.041 17.282      0    0.625    0.785
## 30  tu8 ~~  tu8   0.571 0.041 14.057      0    0.491    0.650
## 31  tu9 ~~  tu9   0.705 0.041 17.275      0    0.625    0.785
## 32 tu10 ~~ tu10   0.693 0.041 16.911      0    0.612    0.773
## 33 tu11 ~~ tu11   0.728 0.040 18.041      0    0.649    0.807
## 34 tu12 ~~ tu12   0.638 0.041 15.467      0    0.557    0.719
## 35 tu13 ~~ tu13   0.684 0.041 16.647      0    0.603    0.764
## 36 tu14 ~~ tu14   0.832 0.036 23.147      0    0.761    0.902
## 37 tu15 ~~ tu15   0.775 0.039 19.949      0    0.699    0.852
## 38 tu16 ~~ tu16   0.525 0.040 13.244      0    0.448    0.603
## 39 tu17 ~~ tu17   0.738 0.040 18.420      0    0.660    0.817
## 40 tu18 ~~ tu18   0.745 0.040 18.675      0    0.667    0.823
## 41 tu19 ~~ tu19   0.746 0.040 18.714      0    0.668    0.824
## 42 tu20 ~~ tu20   0.727 0.040 18.002      0    0.648    0.806
## 43 tu21 ~~ tu21   0.947 0.023 41.482      0    0.902    0.991
## 44 tu22 ~~ tu22   0.737 0.040 18.356      0    0.658    0.815
## 45   F1 ~~   F1   1.000 0.000     NA     NA    1.000    1.000</code></pre>
</div>
<div id="оценка-качества-модели-1" class="section level3">
<h3><span class="header-section-number">28.3.4</span> Оценка качества модели</h3>
<p>Окей, с моделью разобрались, но хочется всё же понять, насколько она хороша. Метрик оценки качества разработано огромное количество — и все их <code>lavaan</code> считает автоматически. Наиболее популярны четыре: <span class="math inline">\(\text{CFI}\)</span>, <span class="math inline">\(\text{TLI}\)</span>, <span class="math inline">\(\text{SRMR}\)</span>, <span class="math inline">\(\text{RMSEA}\)</span>.</p>
<p>Все их можно вытащить достаточно легко:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="cfa.html#cb26-1"></a><span class="kw">fitmeasures</span>(model1, <span class="kw">c</span>(<span class="st">&quot;chisq&quot;</span>, <span class="st">&quot;gfi&quot;</span>, <span class="st">&quot;agfi&quot;</span>,<span class="st">&quot;cfi&quot;</span>, <span class="st">&quot;tli&quot;</span>, <span class="st">&quot;srmr&quot;</span>, <span class="st">&quot;rmsea&quot;</span>))</span></code></pre></div>
<pre><code>##    chisq      gfi     agfi      cfi      tli     srmr    rmsea 
## 1401.716    0.704    0.642    0.659    0.623    0.095    0.119</code></pre>
<p>Как уже говорилось выше, ориентироваться на <span class="math inline">\(\chi^2\)</span> бессмысленно. Для остальных метрик приняты следующие пороговые значения:</p>
<table>
<thead>
<tr class="header">
<th align="left">Метрика</th>
<th align="center">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>GFI</strong> (goodness of fit) (аналог <span class="math inline">\(R^2\)</span>)</td>
<td align="center"><span class="math inline">\(&gt; 0.95\)</span></td>
</tr>
<tr class="even">
<td align="left"><strong>AGFI</strong> (adjusted goodnes of fit)</td>
<td align="center"><span class="math inline">\(&gt; 0.90\)</span></td>
</tr>
<tr class="odd">
<td align="left"><strong>CFI</strong> (comparative fit index)</td>
<td align="center"><span class="math inline">\(&gt; 0.95\)</span></td>
</tr>
<tr class="even">
<td align="left"><strong>TLI</strong> (Tucker Lewis index)</td>
<td align="center"><span class="math inline">\(&gt; 0.95\)</span></td>
</tr>
<tr class="odd">
<td align="left"><strong>RMSEA</strong> (Root Mean Square Error of Approximation)</td>
<td align="center"><span class="math inline">\(&lt; 0.05\)</span></td>
</tr>
<tr class="even">
<td align="left"><strong>SRMR</strong> (Standardized Root Mean Square Residual)</td>
<td align="center"><span class="math inline">\(&lt; 0.05\)</span></td>
</tr>
</tbody>
</table>
<p>В нашем случае все метрики качества за пределами конвенциональных значений, что говорит о низком качестве построенной модели.</p>
<p>Также можно посмотреть на корреляцию остатков модели:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="cfa.html#cb28-1"></a><span class="kw">resid</span>(model1, <span class="dt">type =</span> <span class="st">&#39;cor&#39;</span>)</span></code></pre></div>
<pre><code>## $type
## [1] &quot;cor.bollen&quot;
## 
## $cov
##      tu1    tu2    tu3    tu4    tu5    tu6    tu7    tu8    tu9    tu10  
## tu1   0.000                                                               
## tu2   0.321  0.000                                                        
## tu3   0.068  0.093  0.000                                                 
## tu4  -0.045 -0.065 -0.081  0.000                                          
## tu5  -0.060 -0.004  0.038 -0.006  0.000                                   
## tu6   0.042  0.026  0.028 -0.071  0.051  0.000                            
## tu7   0.050  0.089 -0.047  0.080 -0.064 -0.080  0.000                     
## tu8  -0.015 -0.038  0.191 -0.051  0.050  0.122 -0.086  0.000              
## tu9  -0.021 -0.057  0.107 -0.033  0.169  0.025 -0.161  0.078  0.000       
## tu10 -0.040 -0.004  0.017 -0.033  0.130  0.017 -0.103  0.050  0.197  0.000
## tu11  0.081  0.043 -0.082  0.043 -0.122 -0.039  0.120 -0.080 -0.051 -0.078
## tu12 -0.101 -0.086 -0.137  0.170 -0.012 -0.110  0.042 -0.132 -0.081  0.047
## tu13 -0.011 -0.002 -0.014 -0.055  0.192  0.100 -0.115  0.009  0.159  0.148
## tu14 -0.139 -0.137  0.009  0.068 -0.091 -0.082  0.014  0.053 -0.033 -0.078
## tu15 -0.104 -0.117  0.030  0.096 -0.112 -0.082  0.055  0.098 -0.054 -0.063
## tu16  0.089  0.009 -0.044 -0.052 -0.002  0.139  0.004  0.008 -0.001 -0.045
## tu17 -0.149 -0.124 -0.135  0.140 -0.011 -0.139  0.072 -0.098 -0.074  0.012
## tu18 -0.066  0.039 -0.024 -0.004 -0.115 -0.086  0.098 -0.096 -0.053 -0.118
## tu19 -0.109 -0.051 -0.083  0.066 -0.028 -0.127  0.087 -0.128 -0.069 -0.067
## tu20  0.031  0.060  0.022 -0.030 -0.058  0.049  0.002  0.010 -0.013  0.076
## tu21 -0.151 -0.181 -0.053  0.100 -0.003 -0.103  0.034  0.010  0.028 -0.049
## tu22 -0.057 -0.153 -0.076  0.035 -0.105 -0.003  0.063 -0.049 -0.150 -0.132
##      tu11   tu12   tu13   tu14   tu15   tu16   tu17   tu18   tu19   tu20  
## tu1                                                                       
## tu2                                                                       
## tu3                                                                       
## tu4                                                                       
## tu5                                                                       
## tu6                                                                       
## tu7                                                                       
## tu8                                                                       
## tu9                                                                       
## tu10                                                                      
## tu11  0.000                                                               
## tu12  0.050  0.000                                                        
## tu13 -0.099 -0.036  0.000                                                 
## tu14 -0.012  0.087 -0.097  0.000                                          
## tu15  0.042  0.054 -0.183  0.475  0.000                                   
## tu16  0.027 -0.058  0.008 -0.063 -0.056  0.000                            
## tu17 -0.025  0.281 -0.011  0.038  0.048 -0.071  0.000                     
## tu18  0.159  0.070 -0.065  0.107  0.075 -0.069  0.117  0.000              
## tu19  0.016  0.203 -0.043  0.065  0.023 -0.064  0.312  0.215  0.000       
## tu20 -0.076  0.033  0.033 -0.063 -0.049  0.051 -0.020 -0.054 -0.121  0.000
## tu21  0.077  0.038 -0.008  0.219  0.195 -0.055  0.151  0.034  0.160 -0.167
## tu22  0.102  0.112 -0.082  0.086  0.072  0.034  0.140  0.134  0.185 -0.025
##      tu21   tu22  
## tu1               
## tu2               
## tu3               
## tu4               
## tu5               
## tu6               
## tu7               
## tu8               
## tu9               
## tu10              
## tu11              
## tu12              
## tu13              
## tu14              
## tu15              
## tu16              
## tu17              
## tu18              
## tu19              
## tu20              
## tu21  0.000       
## tu22  0.114  0.000</code></pre>
<p>Значения, большие 0.1, говорят о том, что данная связь недостаточно учтена в модели.</p>
</div>
<div id="визуализация-результатов" class="section level3">
<h3><span class="header-section-number">28.3.5</span> Визуализация результатов</h3>
<p>Визуализировать модель можно с помощью красивой диаграммы. Для этого есть функция <code>semPath()</code>, которая всё за нас сделает:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="cfa.html#cb30-1"></a><span class="kw">semPaths</span>(model1, <span class="st">&#39;std&#39;</span>)</span></code></pre></div>
<p><img src="wlm2021-book_files/figure-html/cfa_model-1.png" width="672" /></p>
<p>На ней сразу отображены и факторный нагрузки, и связи между набладаемыми переменными. Пунктирная стрелка указывает на тот параметр-измерение, относительно которого были нормированы все остальные.</p>
</div>
<div id="модификация-модели" class="section level3">
<h3><span class="header-section-number">28.3.6</span> Модификация модели</h3>
<p>Пакет <code>lavaan</code> настолько хорош, что под капотом строит все модели, которые возможны на предложенных ему данных. И можно вывести так называемые индексы модификации с помощью одноименной функции:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="cfa.html#cb31-1"></a><span class="kw">modificationindices</span>(model1)</span></code></pre></div>
<pre><code>##      lhs op  rhs      mi    epc sepc.lv sepc.all sepc.nox
## 46   tu1 ~~  tu2 127.841  0.848   0.848    0.603    0.603
## 47   tu1 ~~  tu3   5.465  0.188   0.188    0.124    0.124
## 48   tu1 ~~  tu4   2.114 -0.122  -0.122   -0.076   -0.076
## 49   tu1 ~~  tu5   3.625 -0.162  -0.162   -0.100   -0.100
## 50   tu1 ~~  tu6   2.735  0.132   0.132    0.090    0.090
## 51   tu1 ~~  tu7   2.678  0.113   0.113    0.086    0.086
## 52   tu1 ~~  tu8   0.318 -0.044  -0.044   -0.030   -0.030
## 53   tu1 ~~  tu9   0.454 -0.054  -0.054   -0.035   -0.035
## 54   tu1 ~~ tu10   1.747 -0.110  -0.110   -0.070   -0.070
## 55   tu1 ~~ tu11   6.637  0.202   0.202    0.135    0.135
## 56   tu1 ~~ tu12  12.182 -0.271  -0.271   -0.186   -0.186
## 57   tu1 ~~ tu13   0.123 -0.027  -0.027   -0.019   -0.019
## 58   tu1 ~~ tu14  16.848 -0.356  -0.356   -0.213   -0.213
## 59   tu1 ~~ tu15  10.291 -0.264  -0.264   -0.168   -0.168
## 60   tu1 ~~ tu16  12.011  0.256   0.256    0.188    0.188
## 61   tu1 ~~ tu17  22.409 -0.414  -0.414   -0.248   -0.248
## 62   tu1 ~~ tu18   4.282 -0.171  -0.171   -0.108   -0.108
## 63   tu1 ~~ tu19  11.918 -0.293  -0.293   -0.181   -0.181
## 64   tu1 ~~ tu20   0.984  0.081   0.081    0.052    0.052
## 65   tu1 ~~ tu21  17.244 -0.353  -0.353   -0.214   -0.214
## 66   tu1 ~~ tu22   3.294 -0.142  -0.142   -0.095   -0.095
## 67   tu2 ~~  tu3   9.996  0.241   0.241    0.168    0.168
## 68   tu2 ~~  tu4   4.220 -0.162  -0.162   -0.108   -0.108
## 69   tu2 ~~  tu5   0.013 -0.009  -0.009   -0.006   -0.006
## 70   tu2 ~~  tu6   1.062  0.078   0.078    0.056    0.056
## 71   tu2 ~~  tu7   8.148  0.185   0.185    0.150    0.150
## 72   tu2 ~~  tu8   1.934 -0.102  -0.102   -0.075   -0.075
## 73   tu2 ~~  tu9   3.425 -0.139  -0.139   -0.097   -0.097
## 74   tu2 ~~ tu10   0.017 -0.010  -0.010   -0.007   -0.007
## 75   tu2 ~~ tu11   1.885  0.101   0.101    0.072    0.072
## 76   tu2 ~~ tu12   8.655 -0.215  -0.215   -0.156   -0.156
## 77   tu2 ~~ tu13   0.004 -0.004  -0.004   -0.003   -0.003
## 78   tu2 ~~ tu14  16.035 -0.328  -0.328   -0.208   -0.208
## 79   tu2 ~~ tu15  12.633 -0.276  -0.276   -0.185   -0.185
## 80   tu2 ~~ tu16   0.108  0.023   0.023    0.018    0.018
## 81   tu2 ~~ tu17  15.151 -0.321  -0.321   -0.204   -0.204
## 82   tu2 ~~ tu18   1.461  0.094   0.094    0.063    0.063
## 83   tu2 ~~ tu19   2.509 -0.127  -0.127   -0.083   -0.083
## 84   tu2 ~~ tu20   3.563  0.145   0.145    0.099    0.099
## 85   tu2 ~~ tu21  24.233 -0.395  -0.395   -0.253   -0.253
## 86   tu2 ~~ tu22  22.983 -0.354  -0.354   -0.251   -0.251
## 87   tu3 ~~  tu4   6.375 -0.215  -0.215   -0.132   -0.132
## 88   tu3 ~~  tu5   1.388  0.102   0.102    0.062    0.062
## 89   tu3 ~~  tu6   1.146  0.087   0.087    0.058    0.058
## 90   tu3 ~~  tu7   2.165 -0.103  -0.103   -0.077   -0.077
## 91   tu3 ~~  tu8  46.703  0.541   0.541    0.365    0.365
## 92   tu3 ~~  tu9  11.324  0.272   0.272    0.176    0.176
## 93   tu3 ~~ tu10   0.286  0.045   0.045    0.028    0.028
## 94   tu3 ~~ tu11   6.365 -0.201  -0.201   -0.132   -0.132
## 95   tu3 ~~ tu12  20.873 -0.360  -0.360   -0.242   -0.242
## 96   tu3 ~~ tu13   0.189 -0.033  -0.033   -0.023   -0.023
## 97   tu3 ~~ tu14   0.070  0.023   0.023    0.014    0.014
## 98   tu3 ~~ tu15   0.804  0.075   0.075    0.047    0.047
## 99   tu3 ~~ tu16   2.719 -0.123  -0.123   -0.089   -0.089
## 100  tu3 ~~ tu17  17.048 -0.367  -0.367   -0.215   -0.215
## 101  tu3 ~~ tu18   0.524 -0.061  -0.061   -0.038   -0.038
## 102  tu3 ~~ tu19   6.430 -0.218  -0.218   -0.132   -0.132
## 103  tu3 ~~ tu20   0.483  0.057   0.057    0.036    0.036
## 104  tu3 ~~ tu21   2.013 -0.122  -0.122   -0.073   -0.073
## 105  tu3 ~~ tu22   5.383 -0.184  -0.184   -0.121   -0.121
## 106  tu4 ~~  tu5   0.033 -0.016  -0.016   -0.009   -0.009
## 107  tu4 ~~  tu6   6.330 -0.212  -0.212   -0.135   -0.135
## 108  tu4 ~~  tu7   5.480  0.170   0.170    0.121    0.121
## 109  tu4 ~~  tu8   2.856 -0.139  -0.139   -0.089   -0.089
## 110  tu4 ~~  tu9   0.955 -0.082  -0.082   -0.051   -0.051
## 111  tu4 ~~ tu10   0.934 -0.084  -0.084   -0.050   -0.050
## 112  tu4 ~~ tu11   1.569  0.103   0.103    0.065    0.065
## 113  tu4 ~~ tu12  27.970  0.432   0.432    0.277    0.277
## 114  tu4 ~~ tu13   2.743 -0.132  -0.132   -0.086   -0.086
## 115  tu4 ~~ tu14   3.324  0.167   0.167    0.093    0.093
## 116  tu4 ~~ tu15   7.196  0.233   0.233    0.138    0.138
## 117  tu4 ~~ tu16   3.283 -0.141  -0.141   -0.097   -0.097
## 118  tu4 ~~ tu17  15.965  0.369   0.369    0.206    0.206
## 119  tu4 ~~ tu18   0.013 -0.010  -0.010   -0.006   -0.006
## 120  tu4 ~~ tu19   3.551  0.169   0.169    0.097    0.097
## 121  tu4 ~~ tu20   0.754 -0.075  -0.075   -0.045   -0.045
## 122  tu4 ~~ tu21   6.139  0.222   0.222    0.126    0.126
## 123  tu4 ~~ tu22   0.983  0.082   0.082    0.051    0.051
## 124  tu5 ~~  tu6   3.205  0.153   0.153    0.096    0.096
## 125  tu5 ~~  tu7   3.463 -0.137  -0.137   -0.096   -0.096
## 126  tu5 ~~  tu8   2.719  0.137   0.137    0.087    0.087
## 127  tu5 ~~  tu9  24.536  0.422   0.422    0.257    0.257
## 128  tu5 ~~ tu10  14.841  0.342   0.342    0.200    0.200
## 129  tu5 ~~ tu11  12.237 -0.293  -0.293   -0.181   -0.181
## 130  tu5 ~~ tu12   0.145 -0.032  -0.032   -0.020   -0.020
## 131  tu5 ~~ tu13  32.557  0.463   0.463    0.296    0.296
## 132  tu5 ~~ tu14   5.918 -0.226  -0.226   -0.125   -0.125
## 133  tu5 ~~ tu15   9.626 -0.273  -0.273   -0.160   -0.160
## 134  tu5 ~~ tu16   0.003 -0.004  -0.004   -0.003   -0.003
## 135  tu5 ~~ tu17   0.096 -0.029  -0.029   -0.016   -0.016
## 136  tu5 ~~ tu18  10.697 -0.289  -0.289   -0.169   -0.169
## 137  tu5 ~~ tu19   0.630 -0.072  -0.072   -0.041   -0.041
## 138  tu5 ~~ tu20   2.802 -0.146  -0.146   -0.087   -0.087
## 139  tu5 ~~ tu21   0.006 -0.007  -0.007   -0.004   -0.004
## 140  tu5 ~~ tu22   8.984 -0.251  -0.251   -0.155   -0.155
## 141  tu6 ~~  tu7   8.437 -0.201  -0.201   -0.156   -0.156
## 142  tu6 ~~  tu8  25.012  0.393   0.393    0.275    0.275
## 143  tu6 ~~  tu9   0.808  0.072   0.072    0.048    0.048
## 144  tu6 ~~ tu10   0.369  0.051   0.051    0.033    0.033
## 145  tu6 ~~ tu11   1.901 -0.108  -0.108   -0.074   -0.074
## 146  tu6 ~~ tu12  17.871 -0.330  -0.330   -0.229   -0.229
## 147  tu6 ~~ tu13  13.706  0.282   0.282    0.199    0.199
## 148  tu6 ~~ tu14   7.288 -0.235  -0.235   -0.143   -0.143
## 149  tu6 ~~ tu15   7.848 -0.231  -0.231   -0.149   -0.149
## 150  tu6 ~~ tu16  36.394  0.449   0.449    0.335    0.335
## 151  tu6 ~~ tu17  23.929 -0.430  -0.430   -0.261   -0.261
## 152  tu6 ~~ tu18   9.062 -0.250  -0.250   -0.161   -0.161
## 153  tu6 ~~ tu19  19.732 -0.379  -0.379   -0.237   -0.237
## 154  tu6 ~~ tu20   2.982  0.141   0.141    0.092    0.092
## 155  tu6 ~~ tu21   9.830 -0.267  -0.267   -0.164   -0.164
## 156  tu6 ~~ tu22   0.015 -0.010  -0.010   -0.007   -0.007
## 157  tu7 ~~  tu8   8.545 -0.197  -0.197   -0.155   -0.155
## 158  tu7 ~~  tu9  23.144 -0.332  -0.332   -0.250   -0.250
## 159  tu7 ~~ tu10   9.677 -0.223  -0.223   -0.162   -0.162
## 160  tu7 ~~ tu11  12.447  0.239   0.239    0.183    0.183
## 161  tu7 ~~ tu12   1.811  0.090   0.090    0.071    0.071
## 162  tu7 ~~ tu13  12.268 -0.230  -0.230   -0.183   -0.183
## 163  tu7 ~~ tu14   0.152  0.029   0.029    0.020    0.020
## 164  tu7 ~~ tu15   2.431  0.111   0.111    0.080    0.080
## 165  tu7 ~~ tu16   0.016  0.008   0.008    0.007    0.007
## 166  tu7 ~~ tu17   4.374  0.158   0.158    0.108    0.108
## 167  tu7 ~~ tu18   8.009  0.203   0.203    0.146    0.146
## 168  tu7 ~~ tu19   6.387  0.186   0.186    0.131    0.131
## 169  tu7 ~~ tu20   0.004  0.004   0.004    0.003    0.003
## 170  tu7 ~~ tu21   0.757  0.064   0.064    0.044    0.044
## 171  tu7 ~~ tu22   3.375  0.124   0.124    0.095    0.095
## 172  tu8 ~~  tu9   7.062  0.207   0.207    0.141    0.141
## 173  tu8 ~~ tu10   2.902  0.138   0.138    0.090    0.090
## 174  tu8 ~~ tu11   7.016 -0.203  -0.203   -0.140   -0.140
## 175  tu8 ~~ tu12  22.498 -0.361  -0.361   -0.254   -0.254
## 176  tu8 ~~ tu13   0.092  0.023   0.023    0.016    0.016
## 177  tu8 ~~ tu14   2.677  0.139   0.139    0.086    0.086
## 178  tu8 ~~ tu15   9.860  0.253   0.253    0.165    0.165
## 179  tu8 ~~ tu16   0.095  0.022   0.022    0.017    0.017
## 180  tu8 ~~ tu17  10.461 -0.277  -0.277   -0.171   -0.171
## 181  tu8 ~~ tu18   9.908 -0.255  -0.255   -0.166   -0.166
## 182  tu8 ~~ tu19  17.425 -0.347  -0.347   -0.220   -0.220
## 183  tu8 ~~ tu20   0.120  0.028   0.028    0.018    0.018
## 184  tu8 ~~ tu21   0.087  0.025   0.025    0.015    0.015
## 185  tu8 ~~ tu22   2.626 -0.124  -0.124   -0.086   -0.086
## 186  tu9 ~~ tu10  35.433  0.495   0.495    0.310    0.310
## 187  tu9 ~~ tu11   2.247 -0.118  -0.118   -0.078   -0.078
## 188  tu9 ~~ tu12   6.598 -0.200  -0.200   -0.135   -0.135
## 189  tu9 ~~ tu13  23.310  0.367   0.367    0.252    0.252
## 190  tu9 ~~ tu14   0.785 -0.077  -0.077   -0.045   -0.045
## 191  tu9 ~~ tu15   2.334 -0.126  -0.126   -0.079   -0.079
## 192  tu9 ~~ tu16   0.002 -0.004  -0.004   -0.003   -0.003
## 193  tu9 ~~ tu17   4.638 -0.189  -0.189   -0.112   -0.112
## 194  tu9 ~~ tu18   2.325 -0.126  -0.126   -0.079   -0.079
## 195  tu9 ~~ tu19   3.985 -0.170  -0.170   -0.103   -0.103
## 196  tu9 ~~ tu20   0.152 -0.032  -0.032   -0.020   -0.020
## 197  tu9 ~~ tu21   0.510  0.061   0.061    0.036    0.036
## 198  tu9 ~~ tu22  19.138 -0.343  -0.343   -0.227   -0.227
## 199 tu10 ~~ tu11   5.309 -0.188  -0.188   -0.120   -0.120
## 200 tu10 ~~ tu12   2.216  0.120   0.120    0.078    0.078
## 201 tu10 ~~ tu13  20.713  0.360   0.360    0.238    0.238
## 202 tu10 ~~ tu14   4.559 -0.193  -0.193   -0.110   -0.110
## 203 tu10 ~~ tu15   3.244 -0.155  -0.155   -0.093   -0.093
## 204 tu10 ~~ tu16   2.603 -0.124  -0.124   -0.086   -0.086
## 205 tu10 ~~ tu17   0.132  0.033   0.033    0.019    0.019
## 206 tu10 ~~ tu18  11.972 -0.298  -0.298   -0.179   -0.179
## 207 tu10 ~~ tu19   3.848 -0.174  -0.174   -0.102   -0.102
## 208 tu10 ~~ tu20   5.072  0.191   0.191    0.117    0.117
## 209 tu10 ~~ tu21   1.563 -0.111  -0.111   -0.064   -0.064
## 210 tu10 ~~ tu22  14.991 -0.316  -0.316   -0.201   -0.201
## 211 tu11 ~~ tu12   2.435  0.119   0.119    0.082    0.082
## 212 tu11 ~~ tu13   8.793 -0.222  -0.222   -0.154   -0.154
## 213 tu11 ~~ tu14   0.097 -0.027  -0.027   -0.016   -0.016
## 214 tu11 ~~ tu15   1.367  0.095   0.095    0.060    0.060
## 215 tu11 ~~ tu16   0.909  0.069   0.069    0.051    0.051
## 216 tu11 ~~ tu17   0.529 -0.063  -0.063   -0.038   -0.038
## 217 tu11 ~~ tu18  20.356  0.368   0.368    0.233    0.233
## 218 tu11 ~~ tu19   0.218  0.039   0.039    0.024    0.024
## 219 tu11 ~~ tu20   4.777 -0.175  -0.175   -0.113   -0.113
## 220 tu11 ~~ tu21   3.683  0.161   0.161    0.097    0.097
## 221 tu11 ~~ tu22   8.500  0.225   0.225    0.151    0.151
## 222 tu12 ~~ tu13   1.311 -0.085  -0.085   -0.060   -0.060
## 223 tu12 ~~ tu14   6.284  0.212   0.212    0.130    0.130
## 224 tu12 ~~ tu15   2.614  0.130   0.130    0.084    0.084
## 225 tu12 ~~ tu16   4.797 -0.158  -0.158   -0.118   -0.118
## 226 tu12 ~~ tu17  74.800  0.739   0.739    0.452    0.452
## 227 tu12 ~~ tu18   4.581  0.173   0.173    0.112    0.112
## 228 tu12 ~~ tu19  38.595  0.515   0.515    0.324    0.324
## 229 tu12 ~~ tu20   1.059  0.082   0.082    0.054    0.054
## 230 tu12 ~~ tu21   1.018  0.084   0.084    0.052    0.052
## 231 tu12 ~~ tu22  11.882  0.263   0.263    0.180    0.180
## 232 tu13 ~~ tu14   7.118 -0.221  -0.221   -0.137   -0.137
## 233 tu13 ~~ tu15  27.849 -0.415  -0.415   -0.273   -0.273
## 234 tu13 ~~ tu16   0.087  0.021   0.021    0.016    0.016
## 235 tu13 ~~ tu17   0.110 -0.028  -0.028   -0.017   -0.017
## 236 tu13 ~~ tu18   3.634 -0.150  -0.150   -0.099   -0.099
## 237 tu13 ~~ tu19   1.629 -0.103  -0.103   -0.066   -0.066
## 238 tu13 ~~ tu20   0.996  0.078   0.078    0.052    0.052
## 239 tu13 ~~ tu21   0.044 -0.017  -0.017   -0.011   -0.011
## 240 tu13 ~~ tu22   5.945 -0.182  -0.182   -0.127   -0.127
## 241 tu14 ~~ tu15 149.233  1.098   1.098    0.623    0.623
## 242 tu14 ~~ tu16   4.137 -0.163  -0.163   -0.107   -0.107
## 243 tu14 ~~ tu17   1.025  0.097   0.097    0.052    0.052
## 244 tu14 ~~ tu18   7.902  0.254   0.254    0.144    0.144
## 245 tu14 ~~ tu19   2.912  0.158   0.158    0.087    0.087
## 246 tu14 ~~ tu20   2.792 -0.149  -0.149   -0.086   -0.086
## 247 tu14 ~~ tu21  25.427  0.469   0.469    0.254    0.254
## 248 tu14 ~~ tu22   5.210  0.195   0.195    0.117    0.117
## 249 tu15 ~~ tu16   3.520 -0.143  -0.143   -0.100   -0.100
## 250 tu15 ~~ tu17   1.770  0.121   0.121    0.068    0.068
## 251 tu15 ~~ tu18   4.164  0.175   0.175    0.105    0.105
## 252 tu15 ~~ tu19   0.390  0.055   0.055    0.032    0.032
## 253 tu15 ~~ tu20   1.825 -0.114  -0.114   -0.070   -0.070
## 254 tu15 ~~ tu21  21.829  0.412   0.412    0.236    0.236
## 255 tu15 ~~ tu22   3.982  0.162   0.162    0.103    0.103
## 256 tu16 ~~ tu17   5.981 -0.198  -0.198   -0.130   -0.130
## 257 tu16 ~~ tu18   5.643 -0.182  -0.182   -0.126   -0.126
## 258 tu16 ~~ tu19   4.833 -0.173  -0.173   -0.117   -0.117
## 259 tu16 ~~ tu20   3.166  0.134   0.134    0.095    0.095
## 260 tu16 ~~ tu21   2.771 -0.131  -0.131   -0.087   -0.087
## 261 tu16 ~~ tu22   1.417  0.086   0.086    0.063    0.063
## 262 tu17 ~~ tu18  10.890  0.301   0.301    0.170    0.170
## 263 tu17 ~~ tu19  76.770  0.820   0.820    0.452    0.452
## 264 tu17 ~~ tu20   0.315 -0.050  -0.050   -0.029   -0.029
## 265 tu17 ~~ tu21  13.773  0.348   0.348    0.188    0.188
## 266 tu17 ~~ tu22  15.629  0.341   0.341    0.204    0.204
## 267 tu18 ~~ tu19  36.021  0.530   0.530    0.309    0.309
## 268 tu18 ~~ tu20   2.315 -0.129  -0.129   -0.079   -0.079
## 269 tu18 ~~ tu21   0.689  0.074   0.074    0.042    0.042
## 270 tu18 ~~ tu22  14.264  0.307   0.307    0.195    0.195
## 271 tu19 ~~ tu20  11.736 -0.298  -0.298   -0.177   -0.177
## 272 tu19 ~~ tu21  15.280  0.356   0.356    0.198    0.198
## 273 tu19 ~~ tu22  27.050  0.435   0.435    0.268    0.268
## 274 tu20 ~~ tu21  17.133 -0.361  -0.361   -0.210   -0.210
## 275 tu20 ~~ tu22   0.524 -0.058  -0.058   -0.037   -0.037
## 276 tu21 ~~ tu22   7.893  0.236   0.236    0.143    0.143</code></pre>
<p>Индекс модификации показывает, насколько улучшится модель при включении данной связи в её структуру. Данная функцию была разработана для проведения быстрого разведочного анализа и формулирования гипотез для последующих исследований. Но несмотря на благие намерения, велик соблазн уйти на темную сторону исследовательской практики и вводить в модель дополнительные связи, находя им ad hoc объяснения. Не надо так!</p>
</div>
<div id="сравнение-моделей-1" class="section level3">
<h3><span class="header-section-number">28.3.7</span> Сравнение моделей</h3>
<p>Исключительно в учебных целях и ради демонстрации процедуры сравнения моделей мы позволим себе шалость и включим в модель связь <code>tu1    ~~  tu2</code>, у которой наибольший индекс модицикации:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="cfa.html#cb33-1"></a>mdl2 &lt;-<span class="st"> &quot;F1 =~ tu1 + tu2 + tu3 + tu4 + tu5 + tu6 + tu7 + tu8 + tu9 + tu10 + tu11 + tu12 + tu13 + tu14 + tu15 + tu16 + tu17 + tu18 + tu19 + tu20 + tu21 + tu22</span></span>
<span id="cb33-2"><a href="cfa.html#cb33-2"></a><span class="st">tu1 ~~ tu2&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="cfa.html#cb34-1"></a>model2 &lt;-<span class="st"> </span><span class="kw">cfa</span>(mdl2, <span class="dt">data =</span> tolunc)</span>
<span id="cb34-2"><a href="cfa.html#cb34-2"></a><span class="kw">summary</span>(model2)</span></code></pre></div>
<pre><code>## lavaan 0.6-8 ended normally after 34 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        45
##                                                       
##   Number of observations                           405
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                              1259.954
##   Degrees of freedom                               208
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   F1 =~                                               
##     tu1               1.000                           
##     tu2               0.919    0.064   14.423    0.000
##     tu3               0.996    0.103    9.698    0.000
##     tu4               0.899    0.099    9.044    0.000
##     tu5               0.887    0.100    8.865    0.000
##     tu6               1.272    0.117   10.901    0.000
##     tu7               0.752    0.083    9.094    0.000
##     tu8               1.130    0.107   10.518    0.000
##     tu9               0.882    0.096    9.187    0.000
##     tu10              0.943    0.101    9.320    0.000
##     tu11              0.812    0.092    8.810    0.000
##     tu12              1.014    0.101   10.080    0.000
##     tu13              0.876    0.093    9.391    0.000
##     tu14              0.704    0.093    7.556    0.000
##     tu15              0.785    0.093    8.429    0.000
##     tu16              1.147    0.106   10.801    0.000
##     tu17              0.927    0.103    9.008    0.000
##     tu18              0.836    0.096    8.712    0.000
##     tu19              0.873    0.099    8.826    0.000
##     tu20              0.843    0.096    8.800    0.000
##     tu21              0.383    0.082    4.674    0.000
##     tu22              0.823    0.092    8.948    0.000
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .tu1 ~~                                              
##    .tu2               0.857    0.093    9.234    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .tu1               1.615    0.120   13.459    0.000
##    .tu2               1.443    0.107   13.498    0.000
##    .tu3               1.580    0.117   13.459    0.000
##    .tu4               1.683    0.123   13.640    0.000
##    .tu5               1.757    0.128   13.680    0.000
##    .tu6               1.479    0.115   12.885    0.000
##    .tu7               1.155    0.085   13.628    0.000
##    .tu8               1.412    0.108   13.118    0.000
##    .tu9               1.531    0.113   13.605    0.000
##    .tu10              1.656    0.122   13.570    0.000
##    .tu11              1.504    0.110   13.692    0.000
##    .tu12              1.389    0.104   13.321    0.000
##    .tu13              1.390    0.103   13.551    0.000
##    .tu14              1.835    0.132   13.898    0.000
##    .tu15              1.632    0.119   13.766    0.000
##    .tu16              1.267    0.098   12.952    0.000
##    .tu17              1.816    0.133   13.648    0.000
##    .tu18              1.659    0.121   13.712    0.000
##    .tu19              1.728    0.126   13.689    0.000
##    .tu20              1.628    0.119   13.694    0.000
##    .tu21              1.811    0.128   14.131    0.000
##    .tu22              1.463    0.107   13.662    0.000
##     F1                0.832    0.135    6.167    0.000</code></pre>
<p>Сравнение двух моделей выполняется с помощью привычной нам функции <code>anova()</code>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="cfa.html#cb36-1"></a><span class="kw">anova</span>(model1, model2)</span></code></pre></div>
<pre><code>## Chi-Squared Difference Test
## 
##         Df   AIC   BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)    
## model2 208 30112 30292 1260.0                                  
## model1 209 30252 30428 1401.7     141.76       1  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Наблюдаем, что модели статистически значимо различаются. По значениями знакомых нам информационных критериев AIC и BIC можно сделать вывод, что вторая модель лучше описывает данные.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Это, конечно, не единственный критерий, но сейчас для нас — аналитиков — самый важный.<a href="cfa.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="efa.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="further.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["wlm2021-book.pdf", "wlm2021-book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
