---
title: "Введение в курс"
subtitle: "Лекция 0 / 14"
author: "А. Ангельгардт"
date: "HSE UX LAB | Анализ данных + R: мир линейных моделей, 2021"
output: 
  ioslides_presentation:
    widescreen: true
    logo: img/logo.png
---


## Всех категорически приветствую!

И поздравляю с тем, что вы попали на наш курс!

🥳🥳🥳



## Бытие на курсе

Регулируется [вот этим документом](https://docs.google.com/document/d/185h5NQYEKq4PKIrjkOIGIdUM5qrwTllNQidNHkGjTm0/edit?usp=sharing).

А именно, [вот этим его разделом](https://docs.google.com/document/d/185h5NQYEKq4PKIrjkOIGIdUM5qrwTllNQidNHkGjTm0/edit#heading=h.t6mm7dvkuv36).



## Инфополе

- Чат в Telegram
- Google Classroom


# Учеба

## Где? Когда? Сколько?

- Zoom
- ссылка в Google Classroom и в закрепе Telegram-чата

<br>

- с 14.01 до 6.05 по четвергам
- с 18:00 до 21:00 (2 пары)

<br>

- 14 видео-лекций
- 30 практических занятий
- 1 итоговый проект


## Тематический план
[Тут](https://docs.google.com/document/d/185h5NQYEKq4PKIrjkOIGIdUM5qrwTllNQidNHkGjTm0/edit#heading=h.vs3t2b71ndnk)

- три блока
  - R programming
  - теорвер и матстат (+ матликбез)
  - анализ данных
    - от описательных статистик и корреляций
    - до смешанных линейных моделей и факторного анализа


## Мы не изучаем

- анализ временных рядов
- анализ текстовых данных
- машинное обучение и нейросети
- психометрику per se


## Календарный план
[Тут](https://docs.google.com/spreadsheets/d/1egw8RirBdTwUHwZhji1XRlmr115BIBVcSIKsCrJ4YQc/edit?usp=sharing)

- на *первую и вторую неделю* --- одна лекция, на *третью и четвертую* --- тоже
- на *пятой неделе* три лекции, так как математический ликбез
- далее *одна лекция* и *две практических пары* в неделю
- на выполнение итогового проекта отводится одна неделя


## Дедлайны
[Тут](https://docs.google.com/spreadsheets/d/1egw8RirBdTwUHwZhji1XRlmr115BIBVcSIKsCrJ4YQc/edit#gid=824343206)

- на выполнение заданий даётся неделя после практических занятий (*мягкий дедлайн*)
- далее есть ещё четыре дня, чтобы сдать задание, но уже со штрафом (*жёсткий дедлайн*)
- после жёсткого дедлайна задания не принимаются
- есть возможность *вернуть* штрафные баллы!


# Оценивание

## Текущее

- 15 Google Forms
- от 10 до 15 заданий разного уровня сложности
- максимальное количество баллов за одну форму --- 20
- итого *три сотни* баллов за текущий контроль
- за каждый день просрочки мягкого дедлайна снимается 1 балл


## Итоговое

- индивидуальный проект
- анализ реальных данных с применением полученных на курсе знаний и умений
- можно использовать собственные данные
- максимальное количество баллов за проект --- 50
- [критерии и разбалловка](https://docs.google.com/spreadsheets/d/1egw8RirBdTwUHwZhji1XRlmr115BIBVcSIKsCrJ4YQc/edit#gid=96160162) будут доступны не позднее 8.04.2021


## Обратная связь

- оцениваем не только мы вас, но и вы --- нас! 

### По каждому занятию

- перманентно доступная форма для отзывов, жалоб и предложений
- анонимная или нет
- аффорданс попросить хелп


### По завершении тематического блока

- три блока --- три формы фидбека
- за заполнение каждой --- *два дополнительных балла*
- частичная компенсация штрафных баллов за просрочку дедлайнов


## Обратная связь

### По завершении курса

- обратная связь по всему курсу
- ещё два дополнительных балла
- основа, на которой курс дорабатывается, развивается, совершенствуется


## Сертификат

- вот [такой](https://drive.google.com/file/d/1iT6gXGDyiDdzBfSra5kRC8oQ3lG9vdRs/view?usp=sharing)
- надо набрать не менее 240/300 (80%) за текущий контроль (гуглоформы) и не менее 40/50 (80%) за итоговый проект
- мы можем понизить порог, но это не точно


## Есть вопросы?

Пишите в Telegram-чат или в личку!

# До встречи на парах! 😉