---
title: "Введение в статистику"
subtitle: "Лекция 4 / 14"
author: "А. Ангельгардт"
date: "HSE UX LAB | Анализ данных + R: мир линейных моделей, 2021"
output: 
  ioslides_presentation:
    widescreen: true
    logo: img/logo.png
---

# Что такое статистика?

## Статистика

- междисциплинарная область знаний
- практическая деятельность
- изучает массовые явления
- и принципы и методы работы с данными


## Базовые понятия статистики

**Генеральная совокупность** --- множество всех [существующих] анализируемых объектов и сведения о них.

**Объём совокупности** ($N$) --- число единиц, образующих совокупность.

**Выборка** --- часть объектов (объёмом $n$), извлекаемая из генеральной совокупности.


## Базовые понятия статистики

**Показатель (индикатор)** --- количественная характеристика явления.

**Параметр** --- относительно постоянная [от одной совокупности к другой] величина, *характеризующая генеральную совокупность*.

**Выборрчная характеристика (статистика)** --- эмпирический аналог параметра.


# Виды статистических данных

## Статистические данные

совокупность сведений об изучаемом процессе или явлении


## По формату организации

- пространственные
- временные
- пространственно-временные


## По количеству признаков

- одномерные
- многомерные


## По степени обобщённости

- первичные
- агрегированные


## По характеру

- количественные
- категориальные


# Шкалы

## Номинальная (шкала наименований)

- неметрическая
- качественная
- допустимые операции: $=$, $\neq$
- выполняются аксиомы тождества:
  - $A = B \; \mathrm{XOR} \; A \neq B$
  - $A = B \Rightarrow B = A$
  - $A = B \wedge B = C \Rightarrow A = C$
- тип данных: `character`


## Порядковая (ранговая)

- неметрическая
- качественная
- допустимые операции: $=$, $\neq$, $<$, $>$
- допустимо *монотонное преобразование*
- тип данных: `ordered factor` (а также `numeric` [`integer`])


## Интервальная (шкала разностей)

- метрическая
- количественная
- относительный ноль
- допустимые операции: $=$, $\neq$, $<$, $>$, $-$, $+$
- допустимо *линейное преобразование*
- тип данных: `numeric`


## Абсолютная (шкала отношений)

- метрическая
- количественная
- относительный ноль
- допустимые операции: $=$, $\neq$, $<$, $>$, $-$, $+$, $\times$, $\div$ 
- допустимо *преобразование подобия*
- тип данных: `numeric`


# Статистическое моделирование

## Задачи статистики

**В узком смысле:** сжатие информации и наглядное представление результатов

**В широком смысле:** статистическое моделирование


## Статистическое моделирование

- построение [математической] модели, описывающей изучаемое явление
- обобщение результатов выборочного исследования на всю генеральную совокупность


## Этапы статистического моделирования

1) Определение цели и задач моделирования
2) Формализация модели
3) Сбор данных (и предобработка)
4) Спецификация модели
5) Индентификация модели и её анализ
6) Верификация модели


# The end
