---
title: "Лекции"
description: |
  Курс «Анализ данных + R: мир линейных моделей», HSE UX LAB, 2021
author:
  - name: А. Ангельгардт
    url: https://angelgardt.github.io/ru/angelgardt

output: radix::radix_article
---

[Все лекции]()

|№|Видео|Слайды|
|:--|:-------|:---------|
|0|[Введение в курс]()|[Введение в курс](https://angelgardt.github.io/hseuxlab-wlm2021/slides/0-intro)|
|1|[Введение в R]()|[Введение в R](https://angelgardt.github.io/hseuxlab-wlm2021/slides/1-r-intro)|
|2.1|[Работа с реальными данными. Предобработка]()|[Работа с реальными данными. Предобработка](https://angelgardt.github.io/hseuxlab-wlm2021/slides/2-1-tidy)|
|2.2|[Работа с реальными данными. Визуализация]()|[Работа с реальными данными. Визуализация](https://angelgardt.github.io/hseuxlab-wlm2021/slides/2-2-visualization)|
|3.1|[Математический ликбез. Элементы теории множеств]()|[Математический ликбез. Элементы теории множеств](https://angelgardt.github.io/hseuxlab-wlm2021/slides/3-1-set-theory)|
|3.2|[Математический ликбез. Элементы алгебры логики]()|[Математический ликбез. Элементы алгебры логики](https://angelgardt.github.io/hseuxlab-wlm2021/slides/3-2-logic)|
|3.3|[Математический ликбез. Последовательности и функции]()|[Математический ликбез. Последовательности и функции](https://angelgardt.github.io/hseuxlab-wlm2021/slides/3-3-calculus)|
|3.4|[Математический ликбез. Элементы линейной алгебры]()|[Математический ликбез. Элементы линейной алгебры](https://angelgardt.github.io/hseuxlab-wlm2021/slides/3-4-linal)|
|4|[Введение в статистику]()|[Введение в статистику](https://angelgardt.github.io/hseuxlab-wlm2021/slides/4-intro-stat)|
|5.1|[Оценивание параметров в практике статистического анализа]()|[Оценивание параметров в практике статистического анализа](https://angelgardt.github.io/hseuxlab-wlm2021/slides/5-1-estimation)|
|5.2|[Тестирование статистических гипотез]()|[Тестирование статистических гипотез](https://angelgardt.github.io/hseuxlab-wlm2021/slides/5-2-testing)|
|6.1|[Описательные статистики]()|[Описательные статистики](https://angelgardt.github.io/hseuxlab-wlm2021/slides/6-1-descriptives)|
|6.2|[Корреляционный анализ]()|[Корреляционнный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/6-2-correlations)|
|7.1|[Простая линейная регрессия]()|[Простая линейная регрессия](https://angelgardt.github.io/hseuxlab-wlm2021/slides/7-1-linear-regression#1)|
|7.2|[Множественная линейная регрессия]()|[Множественная линейная регрессия]() [Полиномиальная регрессия](https://angelgardt.github.io/hseuxlab-wlm2021/slides/7-2-multiple-linear-regression)|
|8.1|[Дисперсионный анализ]()|[Дисперсионный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/8-1-anova)|
|8.2|[Ковариационный анализ]()|[Ковариационный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/8-2-anсova)|
|9|[Логистическая регрессия]()|[GLM framework](https://angelgardt.github.io/hseuxlab-wlm2021/slides/9-1-glm) [Логистическая регрессия](https://angelgardt.github.io/hseuxlab-wlm2021/slides/9-2-binomial-regression)|
|10.1|[Обобщённые линейные модели для счётных данных]()|[Обобщённые линейные модели для счётных данных](https://angelgardt.github.io/hseuxlab-wlm2021/slides/10-1-poisson)|
|10.2|[Регуляризованная регрессия]()|[Регуляризованная регрессия](https://angelgardt.github.io/hseuxlab-wlm2021/slides/10-2-regularisation)|
|11|[Линейные модели со смешанными эффектами]()|[Линейные модели со смешанными эффектами](https://angelgardt.github.io/hseuxlab-wlm2021/slides/11-glmm)|
|12|[Кластерный анализ]()|[Кластерный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/12-cluster)|
|13.1|[Анализ главных компонент]()|[Анализ главных компонент](https://angelgardt.github.io/hseuxlab-wlm2021/slides/13-1-pca)|
|13.2|[Эксплораторный факторный анализ]()|[Эксплораторный факторный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/13-2-efa)|
|14|[Конфирматорный факторный анализ]()|[Конфирматорный факторный анализ](https://angelgardt.github.io/hseuxlab-wlm2021/slides/14-сfa)|

