---
title: "A0. Как сдать домашку?"
author:
  - name: A. Angelgardt
output: radix::radix_article
---
<link rel="stylesheet" href="style.css">


Скачайте шаблон скрипта по [ссылке](https://drive.google.com/uc?export=download&id=1Ovg6ZnETdoBBXC5DAeFb3K-9Bu3407DX). Если файл открывается некорректно, сделайте `File → Reopen with Encoding… → UTF-8`.

Создайте два вектора `x` и `y`. Поставьте курсов на строку 6 и дважды нажмите `Ctrl + Enter` (`Cmd + Enter`, если у вас Mac).

<div class="item">
6. Вычислите сумму всех элементов двух созданных веторов. Выполните команду в строке 13. Поставьте курсов на строку 13 и нажмите `Ctrl + Enter` (или `Cmd + Enter`). <br>
Результат отобразится в консоли. <br> 
Ответ укажите в соответствующем поле в форме. Введите только одно число.
</div>

<div class="item">
7. Вычислите поэлементное произведение двух имеющихся векторов. В строке 24 напишите команду `x * y` и выполните её, нажав `Ctrl + Enter` (или `Cmd + Enter`). <br>
Результат отобразится в консоли. <br> 
Ответ укажите в соответствующем поле в форме. Скопируйте строку из консоли. Изменять её никак не нужно.
</div>

<div class="item">
8. Если вектор поэлементно умножить на другой вектор, снова получится вектор. Именнно это вы наблюдали в предыдущем задании. А теперь давайте посчитаем сумму всех элементов вектора, который получился после перемножения `x` и `y`. В строке 32 есть заготовка функции `sum()`. Впишите внутрь скобок `x * y` и выполните получившуюся команду аналогично тому, как выполняли предыдущие. <br>
Результат отобразится в консоли. <br> 
Ответ укажите в соответствующем поле в форме. Введите только одно число.
</div>