---
title: "A11. Обобщенные линейные модели для счетных данных. Регуляризованная регрессия"
author:
  - name: A. Angelgardt
  - name: A. Kharitonova
output: radix::radix_article
---

Сегодня мы работаем с [данными о ценах домов](https://www.kaggle.com/srikanthladda/house-price-prediction). [Датасет](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/house_price.csv) содержит характеристики домов, а также цену их продажи (`SalePrice`).

***

**1. Загрузите [данные](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/house_price.csv). Изучите их структуру. При необходимости отредактируйте типы переменных. Удалите служебные столбцы. Для простоты моделей удалите из данных нечисловые переменные, чтобы не использовать их при построении моделей. (2 балла)**

Служебными столбцами являются те, которые не содержат информацию о наблюдениях как объектах продажи, а служат, например, для идентификации наблюдений.

***

**2. В данных есть переменная `GarageCars`. В ней записано количество машин, которое может вместить гараж каждого из домов. Исследуйте взаимосвязи в данных. Выберите _не менее пяти_ предикторов, которые могут быть связаны с этой переменной. (2 балла)**

***

**3. Постройте модель пуассоновской регрессии, в которой зависимой переменной будет `GarageCars`. В качестве предикторов возьмите переменные, которые вы выбрали в предыдущем задании. (1 балл)**

***

**4. Протестируйте получившуюся модель. Проверьте её статистическую значимость, а также значимость отдельных предикторов. Проинтерпретируйте полученные результаты. (2 балла)**

***

**5. Подождите! Ведь мы забыли проверить самое важное! А вдруг этим результатам доверять нельзя? Выполните проверку на наличие сверхдисперсии. Сделайте вывод о качестве модели на основе полученных результатов. (2 балла)**

***

**6. Если обнаружена проблема сверхдисперсии, постройте аналогичную _квазипуассоновскую_ модель. Проверьте её статистическую значимость, а также значимость отдельных предикторов. Проинтерпретируйте полученные результаты. Сравните результаты с пуассоновской моделью.**

**Если проблема сверхдисперсии не обнаружена, упростите имеющуюся модель. Если все предикторы модели значимы и её нельзя упростить, удалите один или несколько предикторов и сравните две модели с помощью информационных критериев. (1 балл)**

***

**7. Постройте модель регуляризованной регрессии, которая будет предсказывать цену продажи (`SalePrice`) домов на основе их характеристик. Используйте тип регрессии, позволяющий получить оценки для всех параметров модели. (2 балла)**

***

**8. Выведите коэффициенты для варианта модели с наименьшей ошибкой. Какие из параметров оказывают наибольшее влияние на цену домов? (1 балл)**

***

**9. Постройте модель регуляризованной регрессии, которая будет предсказывать цену продажи (`SalePrice`) домов на основе их характеристик. Используйте тип регрессии, позволяющий отобрать предикторы. (2 балла)**

***

**10. Выведите коэффициенты для варианта второй модели с наименьшей ошибкой и для варианта модели с ошибкой в пределах одного стандартного отклонения от минимальной. Сравните полученные результаты. (2 балла)**

***

**11. Постройте две модели, в которую будут включены только те предикторы, которые не обнулились LASSO-регрессией (модель с наименьшей ошибкой). Зависимой переменной оставьте `SalePrice`. Первая модель --- множественная линейная регрессия, вторая --- ridge-регрессия. Сравните предказательную силу двух моделей с помощью изученных метрик. (3 балла)**

