---
title: "A14. Анализ главных компонент и эксплораторный факторный анализ"
author:
  - name: A. Angelgardt

output: radix::radix_article
---

Сегодня мы работаем с [данными про состав стекла](https://www.kaggle.com/uciml/glass).

Датасет содержит следующие переменные:

* `RI` --- refractive index
* `Na` --- Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4--10)
* `Mg` --- Magnesium
* `Al` --- Aluminum
* `Si` --- Silicon
* `K` --- Potassium
* `Ca` --- Calcium
* `Ba` --- Barium
* `Fe` --- Iron
* `Type of glass`:
  - `1` --- building_windows_float_processed 
  - `2` --- building_windows_non_float_processed 
  - `3` --- vehicle_windows_float_processed 
  - `4` --- vehicle_windows_non_float_processed (none in this database) 
  - `5` --- containers 
  - `6` --- tableware 
  - `7` --- headlamps

***

**1. Загрузите [датасет](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/glass.csv). Проверьте типы переменных. Если есть такие переменные, которые по своему содержанию должны быть другого типа, приведите их к нужному типу. Приведите данные к виду tidy data --- cделайте необходимые преобразования с переменными, если они потребуются. (2 балла)**

***

**2. Проведите разведочный анализ. Насколько хорошо данные подходят для проведения экслораторного факторного анализа и анализа главных компонент? Все ли переменные будут включены в эти виды анализа? Постройте необходимые визуализации. (2 балла)**

***

**3. Выполните анализ главных компонент. Не забудьте учесть особенности данных. (2 балла)**

***

**4. Проанализируйте результаты анализа главных компонент. Можно ли сократить размерность признакового пространства? Если да, то до скольки измерений? На основе каких показателей был сделан такой вывод? (3 балла)**

***

**5. Визуализируйте взаимосвязи между выделенными главными компонентами и переменными датасета, которые не были включены в анализ. Попробуйте предложить интерпретацию выделенных главных компонент. (1 балл)**

***

**6. Проведите эксплораторный факторный анализ. Постройте _минимум три_ факторные модели. (2 балла)**

Не забудьте сохранить значение самих факторов для выполнения дальнейших заданий.

***

**7. Сравните получившиеся модели. Сделайте вывод о качестве полученной факторной структуры. Сколько, на ваш взгляд, скрытых факторов содержится в данных? Обоснуйте своё решение. (3 балла)**

***

**8. Как можно было бы улучшить выбранную факторную модель? Предложите возможные варианты с опорой на результаты анализа. (2 балла)**

***

**9. Визуализируйте взаимосвязи между выделенными факторами и переменными датасета, которые не были включены в анализ. Попробуйте предложить интерпретацию выделенных главных компонент. (1 балл)**

***

**10. Сопоставьте результаты эксплораторного факторного анализа и анализа главных компонент. Различается ли структура данных, обнаруженная различными методами? (2 балла)**
