---
title: "A4. Предобработка данных. Визуализация"
author:
  - name: A. Angelgardt
  - name: A. Kharitonova
output: radix::radix_article
---
<link rel="stylesheet" href="style.css">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Ну что же, начинаем работать со сложными задачками на вполне реальных данных. Да, да, у нас есть [датасеты](https://drive.google.com/uc?export=download&id=1Lq0oV7ZwAQb9XVUawy9Oau9H5XyTBKdm) с данными одного исследователя. Вот описание его исследования:

***

Эксперимент был направлен на изучение гибридного зрительного поиска. Испытуемому необхожимо было искать объекты из определенной категории. В качестве независимых переменных варьировались так называемые *visual setsize* и *memory setsize*, то есть количество стимулов, предъявляемых респонденту на экране монитора, и количество категорий, которые нужно было запомнить. Кроме того, использовались категории двух уровней --- *базовые и суперординатные*.

Данные располагаются в двух файлах. В файле `base.xlsx.` содержаться данные из группы испутыемых, которым предлагались базовые категории, в файле `super.xlsx` --- данные из группы испутыемых, которым предлагались суперординатные категории.

На листе `cor_answ` в каждом файле есть данные по точности для каждого сочетания условий. Сочетания условий кодируются следующим образом: например, `1_stim_8` обозначает, что *memory setsize* был равен 1, а *visual setsize* был равен 8. То есть первое число задаёт *memory setsize*, второе =  *visual setsize*. На этом же листе с правого края есть соцдем респондентов --- пол и возраст. На листе `Time` располагаются аналогичным образом организованные данные по времени реакции (нажатие на клавишу).

***


**2) Скачайте [архив с данными](https://drive.google.com/uc?export=download&id=1Lq0oV7ZwAQb9XVUawy9Oau9H5XyTBKdm). Разархивируйте файлы. C помощью уже знакомых вам функций из пакета `readxl` импортируйте данные в R. У вас должно получиться 4 датасета с данными с 4-х листов Excel-файлов.**

*** 

Итак, как вы можете видеть, данные вообще не подходят под формат tidy data, к которому мы стремимся, давайте это исправим.

***


**3) Начнем собирать все необходимое в один датасет. Для начала удалите пустые строки или столбцы из загруженных датасетов. Соцдем выгрузите в отдельный датасет.**

***

**4) Переведите данные в длинный формат. В датасете должны содержаться следующие колонки: `id` --- номер испытуемого, `visual_setsize` --- количество стимулов в пробе, `memory_setsize` --- количество категорий для запоминания, `reaction_time`/`accuracy` --- время реакции / точность (в зависимости от датасета). При необходимости переименуйте столбцы.**

***

**5) Создайте новую переменную `group`, содержащую информацию об уровне категории --- базовая (`base`) или суперординатная (`super`).**

***

**6)Теперь можно объединять все наши данные в один датасет. Итоговый датасет должен содержать следующие столбцы:**

* **`id` --- идентификатор испытуемого**
* **`age` --- возраст испытуемого**
* **`sex` --- пол испытуемого**
* **`group` --- уровень категорий**
* **`visual_setsize` --- количество стимулов в пробе**
* **`memory_setsize` --- количество категорий для запоминания**
* **`reaction_time` --- время реакции**
* **`accuracy` --- точность**

***

**7) Давайте посмотрим какие-нибудь описательные статистики для групп по уровню категории. Посмотрите среднее, минимальное и максимальное время реакции по всем сочетаниях независимых переменных.**

***

**8) Давайте сделаем график в котором посмотрим зависимость между возрастом респондента и временем реакции в условии с тремя категориями для запоминания и восемью стимулами в пробе. Нарисуйте соответствующий график. Добавьте линию тренда.**

***

**9) А теперь добавим на график группировку по уровню категории: базовая или суперординатная. Пусть базовая будет синего цвета, а суперординатная --- оранжевого. Обязательно добавьте легенду и линии тренда --- для каждого уровня категории свою!**

***

**10) А теперь чуть сложней, мы ведь посмотрели только по одному условию эксперимента. Давайте посмотрим распределение точности в различных visual setsize и memory setsize. Постройте такой график, который будет состоять из нескольких субграфиков. Сделайте гистограммы цветными!**

***

**11) Следующий график! Давайте сделаем ящики с усами и посмотрим распределение времени реакции в заивимости от уровня категорий для групп женского и мужского пола. Измените тему графика. Переименуйте оси, чтобы их названия были написаны по-русски.**

***

**12) А теперь давайте посмотрим взаимосвязи между visual setsize и точностью, а также между memory setsize и точностью. Создайте два графика. Затем объедините их в одну картинку (с помощью кода).**

***

**13) Посмотрите информацию про функции `scale_...` (`scale_color_...`, `scale_fill_...` и др.). Что она делает? Придумайте сложную (отображающую зависимости нескольких переменных) визуализацию и создайте её с применением функций `scale_...`. В погоне за сложностью помните про понятность графика.**


