---
title: "A7. Описательные статистики. Корреляционный анализ"
author:
  - name: A. Angelgardt
  - name: A. Kharitonova
output: radix::radix_article
---
<link rel="stylesheet" href="style.css">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Давайте скачаем датасет с успеваемостью студентов по [ссылке](https://www.kaggle.com/spscientist/students-performance-in-exams/tasks). Потренируемся на нем.

***

**7) Рассчитайте дисперсию и стандартное отклонение для переменной Math Score (баллы по математике).**

***

**8) Для той же переменной отберите все значения из 4-го квартиля, сохраните в отдельную переменную.**

***

**9) Давайте построим боксплот для переменной Writing Score. Сколько всего выбросов?**

***

**10) Работаем все с тем же датасетом. Давайте проведем анализ о наличии линейной взаимосвязи между баллами за чтение и письмо. Нарисуйте график, который потенциально отражал бы эту зависимость. Каковы ваши прогнозы?**

***

**11) Какой тест лучше всего применить?**

а) Спирмена

б) Пирсона

в) Кендалла

***

**12) А теперь давайте проверим, применив этот тест, в ответ впишите получившееся значение коэффициента корреляции.**

***

**13) А если посмотреть корреляции между всеми баллами за все предметы? Постройте график.**

***

**14) Ну и на последок рассчитайте коэффициент для переменных gender и test preparation, чтобы посмотреть есть ли зависимости между наличием подготовки и полом студента. Подумайте, каким методом стоит воспользоваться.**
