---
title: "A8. Простая и множественная линейная регрессия"
author:
  - name: A. Angelgardt
  - name: A. Kharitonova
output: radix::radix_article
---
<link rel="stylesheet" href="style.css">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> Поздравляем, мы начинаем работать с вполне реальными данными!

Перед вами [данные китайской автокомпании Geely Auto](https://www.kaggle.com/hellbuoy/car-price-prediction), где представлены параметры их автомобилей. Компания стремится выйти на американский рынок, создав там свое производственное подразделение и производя автомобили на местном уровне, чтобы составить конкуренцию своим американским и европейским коллегам.

Они заключили контракт с автомобильной консалтинговой компанией, чтобы понять факторы, от которых зависит ценообразование автомобилей. В частности, они хотят понять факторы, влияющие на ценообразование автомобилей на американском рынке, поскольку они могут сильно отличаться от китайского рынка.

Компания хочет знать:

* Какие переменные важны для прогнозирования цены автомобиля
* Насколько хорошо эти переменные описывают цену автомобиля

Давайте начнем идти к этой цели!

***

**1) Загрузите [датасет](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/CarPrice_Assignment.csv), просмотрите первые несколько строк, выведите типы переменных, при необходимости отредактируйте типы переменных.** (2 балла)

Например, переделайте переменные со строковыми значениями чисел в числовой формат.
*Подсказка: `sub()`*

***

**2) Как обычно предобработайте данные. Уберите все строки с пропущенными значениями, удалите выбросы из датасета.** (2 балла)

***

**3) Компания предположила, что количество лошадиных сил будет предсказывать стоимость крайне сильно, объясняя около 25% изменчивости данных. Постройте график, а затем проверьте эту гипотезу.** (3 балла)

***

**4) Постройте множественную линейную регрессию, учитывая комментарий о том, что переменная о расположении двигателя не имеет значения (подумайте также, почему).** (3 балла)

Можно использовать все переменные из датасета, можно только часть. Предложите минимальное обоснование, почему Вы решили использовать эти переменные.

***

**5) Посмотрите все необходимые параметры модели, укажите три переменные, наиболее сильно влияющие на стоимость.** (3 балла)

***

**6) Выполните все диагностики модели. Опишите результаты диагностики.** (3 балла)

***

**7) Предложите способы, как можно было бы улучшить модель. Постройте ещё одну модель и сравните её с предыдущей. Опишите результаты сравнения.** (4 балла)
