---
title: "A9. Дисперсионный анализ. Ковариационный анализ"
author:
  - name: A. Angelgardt
output: radix::radix_article
---
<link rel="stylesheet" href="style.css">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> Сегодня анализируем экспериментальные данные!

Вам доступны [данные поведенческого исследования](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/design_fastsearch.csv), проведенного на благо юзабилити-индустрии. В исследовании изучалось влияние перцептивных характеристик иконок на эффективность их обнаружения. Да, снова зрительный поиск. Ну, шо поделать…

В эксперименте вариаровались следующие **параметры стимулов**:

* наличие / отсутствие градиента: `f` --- flat, `g` --- градиент
* наличие отсутствие тени: `s` --- shadow

Также традиционно вариаровалось число стимулов в пробе --- `3`, `6`, `9`. Перед каждой пробой испытуемому предъявлялась целевая иконка. Если испытуемый нашёл целевую иконку среди всех предложенных, он нажимал стрелку вправо (`right`), если не обнаружил --- стрелку слево (`left`). Так как ответ давался клавишами, в дизайне исследования были предусмотрены «пробы-ловушки», в которых не было целевого стимула. Пробы, в которых целевой стимул присутствовал, обозначены как `p`, а пробы, в которых целевой стимул отсутствовал --- `a`.

Сочетания условий закодированы в переменной `cond`. Таким образом,

* строка `f3_p` означает, что эта проба с *тремя* (`3`) *плоскими* (`f`) стимулами *без тени* (отсутствует `s`) *содержала целевой* стимул (`p`)
* такая запись: `gs9_a` будет кодировать пробу с *девятью* (`9`) *градиентными* (`g`) стимулами *с тенью* (`s`), в которой *отсутстует целевой* стимул (`a`).

Другие переменные в датасете:

* `key` --- ответ испытуемого (`left` / `right`)
* `time` --- время реакции (мс)
* `id` --- идентификатор испытуемого

Глобальные вопросы к датасету:

* Какие факторы влияют на эффективность обнаружения иконок?
* И как они это делают --- каково направление влияния?


***

**1) Загрузите [датасет](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/design_fastsearch.csv), изучите его структуру, выведите типы переменных, при необходимости отредактируйте типы переменных.** (1 балл)

***

**2) Предобработайте данные. Уберите все строки с пропущенными значениями, если такие есть, удалите выбросы из датасета. Подумайте, как должы выглядеть данные, чтобы вы смогли ответить на вопросы, заданные к датасету** (3 балла)

<details>
<summary>*Подсказка*</summary>
Какую манипуляцию необходимо провести, чтобы было возможно включить в модель в качестве предикторов экспериментальные независимые переменные, а также посчитать точность (accuracy)?

<details>
<summary>*Ещё подсказка*</summary>
Необходимо разбить переменную `cond` на переменные `setsize`, `gradient`, `shadow` и `target`.
</details>
</details>

***

**3) Аггрегируйте данные. Создайте тиббл, который будет содержать усреднённое время реакции и точность для каждого респондента по всем сочетаниям условий. Для расчёта усреднённого времени реакции возьмите только корректные пробы.** (3 балла)

<details>
<summary>*Подсказка*</summary>
Испытуемый корректно выполнил пробу, если

* в ней *присутствовал* стимул, и он дал ответ `right`
* в ней *отсутствовал* стимул, и он дал ответ `left`
</details>

***

**4) Постройте линейную модель в параметризации индикаторов. В качестве предикторов включите в модель параметры стимулов, которые варьировались в эксперименте, а также их взаимодействие. Выведите коэффициенты модели. Дайте им интерпретацию.** (3 балла)

***

**5) Постройте линейную модель в параметризации эффектов. В качестве предикторов включите в модель параметры стимулов, которые варьировались в эксперименте, а также их взаимодействие. Выведите коэффициенты модели. Дайте им интерпретацию.** (4 балла)

***

**6) Проведите дисперсионный анализ. Подумайте, какой из типов сумм квадратов необходимо использовать в данном случае и почему. Проведите попарные сравнения, если это необходимо. Визуализируйте полученные результаты и кратко интерпретируйте их.** (4 балла)

***

**7) Можно ли на предложенных данных провести ковариационный анализ, если в качестве ковариаты мы хотим учесть влияние количества стимулов, предъявляемых в пробе? Проведите необходимые проверки, интерпретируйте их результаты. Если провести ковариационный анализ возможно, постройте модель, в которой в качестве факторов будут включены наличие/отсутствие градиента и наличие/отсутствие тени, а в качестве ковариаты --- число стимулов в пробе.** (2 балла)

Мы с вами не обсуждали отдельно ковариационный анализ, так как он по своей сути являет собой не что иное как множественную линейную регрессию с категориальными и количественными предикторами. Только с некоторой особенностью. Всю нужную информацию вы сможете найти [здесь](https://angelgardt.github.io/hseuxlab-wlm2021/book/ancova.html).
