# Введение в статистику {#stats_intro}

> А чем мы тут занимаемся вообще?

## Исходные понятия статистики

**Статистика** --- это междисциплинарная область знаний, а также практической деятельности, изучающая массовые явления, а также прицнипи и методы работы с данными, характеризующими эти явления.

**Генеральная совокупность** --- множество всех [существующих] исследуемых объектов, а также сведения о них.

**Объем совокупности** --- число единиц, образующих совокупность.

Из генеральной совокупности объёмом $N$ извлекается **выборка** объёмом $n$.

Объекты нашей генеральной (или выборочной) совокупности обладают определёнными **признаками**. Какие-то из этих признаков мы изучаем.

**Показатель (индикатор)** --- количественная характеристика признака, которым обладают наши объекты изучения.

**Параметр** --- относительно постоянная [от одной совокупности к другой] величина, характеризующая генеральную совокупность. Эта величина неизвестна, и никогда не будет известна, поэтому может быть только предсказана с определённой статистической точностью.

**Выборочная характеристика (статистика)** --- эмпирический (измеримый) аналог параметра.


## Виды статистических данных

**Статистические данные** --- совокупность сведений об изучаемом процессе или явлении.

1. По формату организации
  - пространственные
  - временные
  - пространственно-временные
2. По количеству признаков
  - одномерные
  - многомерные
3. По характеру
  - количественные
  - качественные
4. По степени обобщенности
  - первичные
  - агрегированные

## Шкалы

|Шкала|Тип шкалы|Тип данных|Допустимые операции|
|:----|:--------|:---------|:------------------|
|*Номинальная (шкала наименований)*|Неметрическая|Качественные|$=$, $\neq$|
|*Порядковая (ранговая)*|Неметрическая|Качественные|$=$, $\neq$, $>$, $<$|
|*Интервальная (шкала разностей)*|Метрическая|Количественные|$=$, $\neq$, $>$, $<$, $+$, $-$|
|*Абсолютная (шкала отношений)*|Метрическая|Количественные|$=$, $\neq$, $>$, $<$, $+$, $-$, $\times$, $\div$|

|Шкала|Ноль|Допустимые преобразования|
|:----|:---|:------------------------|
|*Номинальная (шкала наименований)*|Отсутствует|---|
|*Порядковая (ранговая)*|Отсутствует|Монотонное преобразование|
|*Интервальная (шкала разностей)*|Относительный|Линейное преобразование|
|*Абсолютная (шкала отношений)*|Абсолютный|Преобразование подобия|


## Задачи статистики

**В узком смыле:** сжатие информации и наглядное представление результатов.

**В широком смысле:** *статистическое моделирование* --- обощение результатов выборочного исследования на всю генеральную совокупность.

### Этапы статистического моделирования

* **Определение целей и задач моделирования** --- сопряжено с определением целей и задач исследования в целом.
* **Формализация модели** --- формулирование модели в самом общем математическом виде, т. е. по факту выбор из множества моделей той, которая будет пригодна для описания предполагаемых закономерностей.
* **Сбор данных и их предобработка**
* **Спецификация модели** --- формулирование модели для данного исследования в общем виде, т. е. без конкретных коэффициентов, но с включением всех переменных (в т. ч. их взаимодействий) в математическую модель.
* **Идентификация модели** --- подбор коэффициентов модели.
* **Анализ модели** --- проверка статистической значимости модели и её коэффициентов, а также проверка выполнения математических допущений данной модели.
* **Верификация модели** --- тестирование модели на новом наборе данных, с которым она ещё не знакома.
